In [1]:
%load_ext autoreload
%autoreload 2
from sqlalchemy import create_engine
import sqlalchemy
import pandas as pd
import os
from datetime import datetime, timedelta
from dotenv import load_dotenv

In [2]:
from oceanobs.buoys.simcosta import Simcosta

In [13]:
s = Simcosta(n_workers=16)

In [85]:
stations = s.get_stations()

In [86]:
# results = s.get_data(station=stations[6])

In [90]:
results = s.get(stations = stations)

No data available for the station 1                      | 0/50 [00:00<?, ?it/s]
No data available for the station 14             | 1/50 [00:01<01:12,  1.49s/it]
No data available for the station 313
No data available for the station 308
No data available for the station 200
No data available for the station 999
No data available for the station 513
No data available for the station 301
No data available for the station 510
No data available for the station 504            | 9/50 [00:01<00:05,  7.18it/s]
No data available for the station 514
No data available for the station 300           | 12/50 [00:02<00:05,  7.35it/s]
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=397&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
No data available for the station 309
No data available for the station 220
No data available for the station 3
No data available for the station 1
No data available for the station 502           | 19/50 [00:02<00:03,  9.25it/s]
No data available for the station 306
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3330&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/metereo_data?boiaID=17&type=json&time1=1737073798&time2=1737505798&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
Error getting data from https://simcosta.furg.br/api/metereo_data?boiaID=19&type=json&time1=1737073798&time2=1737505798&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3339&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3340&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
No data available for the station 311▍          | 29/50 [00:04<00:02,  9.35it/s]
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3337&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3341&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3335&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3334&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3342&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
No data available for the station 312
Downloading data:  80%|████████████████████     | 40/50 [00:05<00:01,  9.56it/s]Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3333&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3332&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
No data available for the station 314
Error getting data from https://simcosta.furg.br/api/intrans_data?boiaID=3336&type=json&time1=1737073798&time2=1737505798&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Downloading data: 100%|█████████████████████████| 50/50 [00:08<00:00,  5.71it/s]
/mnt/soutobias/code/oceanoslive/oceanoobsbrasil/oceanobs/oceanobs.py:54: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat(results, axis=0, join="outer", ignore_index=True)

In [89]:
pd.concat(results)

/tmp/ipykernel_57904/2640668940.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(results)

,date_time,sal,turb,chl,wtmp,wtmp2,id,dewpt,rh,atmp,...,wvdir,wvspread,tsig,tp5,hm0,zcn,hmt,mdecl,cdir,cspd
0,2025-01-17 01:01:30+00:00,4.55456,22.03989,1.56889,None,27.08,210,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-17 02:01:30+00:00,5.81067,17.36322,1.39378,None,26.7,210,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-01-17 03:01:30+00:00,7.75167,15.07867,1.14444,None,26.44,210,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-17 04:01:30+00:00,8.65211,13.11633,1.03700,None,26.29,210,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-01-17 05:01:30+00:00,5.97444,21.34750,1.72700,None,25.62,210,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1730,2025-01-18 05:20:00+00:00,NaN,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1731,2025-01-18 05:21:00+00:00,NaN,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1732,2025-01-18 05:22:00+00:00,NaN,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1733,2025-01-18 05:23:00+00:00,NaN,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1734,2025-01-18 05:24:00+00:00,NaN,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
results[9].columns

Index(['date_time', 'swvht', 'tp', 'sst', 'wspd', 'wdir', 'id'], dtype='object')

In [76]:
pd.concat(results[8:10])

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [55]:
results = [df.reset_index(drop=True) for df in results]
final_result = pd.concat(results, ignore_index=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [11]:
results = results.rename(columns={
    "timestamp": "date_time",
    "Avg_Turb": "turb",
    "Avg_Chl": "chl",
    "Avg_Dew": "dewpt",
    "Avg_Hmt": "rh",
    "Avg_Air_Tmp": "atmp",
    "Avg_Air_Press": "pres",
    "Gust_Sp": "gust",
    "Avg_Wnd_Sp": "wspd",
    "Avg_Wnd_Dir_N": "wdir",
    "Avg_Sol_Rad": "srad",
    "Hsig": "swvht",
    "Tp": "tp",
    "Hmax": "mxwvht",
    "Havg": "whgt",
    "Tavg": "sst",
    "H10": "h10",
    "T10": "t10",
    "Avg_Wv_Dir": "wvdir",
    "Avg_Wv_Spread": "wvspread",
    "Tsig": "tsig",
    "Tp5": "tp5",
    "HM0": "hm0",
    "ZCN": "zcn",
    "Avg_Sal": "sal",
    "Avg_W_Tmp1": "wtmp",
    "Avg_W_Tmp2": "wtmp2",
    "Hmt": "hmt",
    "Avg_Wnd_Dir": "wdir",
    "M_Decl": "mdecl",
    "C_Avg_Dir_N": "cdir",
    "C_Avg_Spd": "cspd",
    "C_Avg_Dir": "cdir",
    "Avg_Wv_Spread_N": "wvspread",
    "Avg_Wv_Dir_N": "wvdir",
})

In [12]:
results

,date_time,YEAR,MONTH,DAY,HOUR,MINUTE,SECOND,turb,chl,dewpt,...,wtmp,wtmp2,hmt,wdir,mdecl,cdir,cspd,cdir,wvspread,wvdir
0,2025-01-17T00:21:40.000Z,2025,1,17,0,21,40,17.32,6.24,NaN,...,26.03,25.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-17T00:51:40.000Z,2025,1,17,0,51,40,15.10,5.74,NaN,...,25.8,25.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-01-17T01:21:40.000Z,2025,1,17,1,21,40,18.26,6.29,NaN,...,25.88,25.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-17T01:51:40.000Z,2025,1,17,1,51,40,18.33,6.09,NaN,...,25.77,25.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-01-17T02:21:40.000Z,2025,1,17,2,21,40,14.09,5.39,NaN,...,25.62,25.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,2025-01-18T05:20:00.000Z,2025,1,18,5,20,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1744,2025-01-18T05:21:00.000Z,2025,1,18,5,21,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1745,2025-01-18T05:22:00.000Z,2025,1,18,5,22,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1746,2025-01-18T05:23:00.000Z,2025,1,18,5,23,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1747,2025-01-18T05:24:00.000Z,2025,1,18,5,24,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
from oceanoobsbrasil.db import GetData
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
bd = GetData()

In [4]:
bd.get(table='stations', institution=['=', 'simcosta'], data_type=['=', 'tide'])

,id,name,lat,lon,data_type,institution,url,flag
0,1156,DHN - RJ,-22.884722,-43.13222,tide,simcosta,304,True
1,873,Rio Grande 1 – RS,-32.188100,-52.08190,tide,simcosta,301,True
2,874,São José do Ribamar – MA,-8.393100,-34.96000,tide,simcosta,302,True
3,875,Tramandaí – RS,-30.005000,-50.12890,tide,simcosta,305,True
4,877,Imbituba – SC,-28.231100,-48.65000,tide,simcosta,308,True
5,878,Ilhabela – SP,-23.773600,-45.35470,tide,simcosta,309,True
6,879,Suape – PE,-8.393100,-34.96000,tide,simcosta,311,True
7,876,Pecém – CE,-3.531100,-38.79310,tide,simcosta,307,True

In [17]:
df = bd.get(table='data_stations', station_id=['in', [2675]])

In [18]:
df.shape

(0, 24)

In [7]:
bd.post(table='data_stations', df=df)

DELETE FROM data_stations WHERE true AND station_id in (902) AND date_time >= '2021-09-06 00:21:00'

In [12]:
import time
import datetime
import operator
import urllib.request, json

import numpy as np
from oceanoobsbrasil.buoys.simcosta import Simcosta
from oceanoobsbrasil.tides.simcosta import SimcostaTide

In [13]:
s = Simcosta()

In [14]:
s.get()

14
Nao ha dados para essa boia
13
Nao ha dados para essa boia
3
Nao ha dados para essa boia
210
https://simcosta.furg.br/api/intrans_data?boiaID=210&type=json&time1=1705775385&time2=1705861785&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
ok
504
https://simcosta.furg.br/api/intrans_data?boiaID=504&type=json&time1=1705775385&time2=1705861785&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
ok
12
Nao ha dados para essa boia
515
https://simcosta.furg.br/api/intrans_data?boiaID=515&type=json&time1=1705775385&time2=1705861785&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
ok
510
https://simcosta.furg.br/api/intrans_data?boiaID=510&type=json&time1=1705775385&time2=1705861785&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Nao ha dados para essa boia
6
Nao ha dados para essa boia
516
https://simcosta.furg.br/api/intrans_data?boiaID=516&type=json&time1=1705775385&time2=1705861785&params=H10,HAvg,Hsig,HM0,Avg_Wv_Dir,Hmax,ZCN,Tp5,Tz,TAvg,T10,Tsig,Avg_Wv_Spread,Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Chl,Avg_Turb,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Air_Press,Avg_Sol_Rad,Avg_Air_Tmp,Avg_Hmt,Avg_Hmt,Avg_Wnd_Sp
Nao ha dados para essa boia

In [37]:
s.stations.iloc[0].url

'3'

In [50]:
url_address = f"https://simcosta.furg.br/api/intrans_data?boiaID=510&type=json&time1={s.start_date}&time2={s.end_date}&params=Avg_Air_Press,Avg_Wnd_Dir_N,Gust_Sp,Avg_Dew,Avg_Sol_Rad,Avg_Air_Tmp,Hmt,Avg_Hmt,Avg_Wnd_Sp,Wv_H10,Wv_Havg,Wv_Hsig,Wv_HM0,Wv_Avg_Dir,Wv_Hmax,Wv_ZCN,Wv_Tp5,Wv_Tz,Wv_Tavg,Wv_T10,Wv_Tsig,Wv_Avg_Spread,Wv_Tp,Avg_Sal,Avg_W_Tmp1,Avg_W_Tmp2,Avg_Fluo,Avg_DO,Avg_DO,Avg_Turb"
with urllib.request.urlopen(url_address) as url:
    data = json.loads(url.read().decode())
    s.data = pd.DataFrame(data)

In [52]:
s.result = s.data

In [57]:
s.result['date_time'] = pd.to_datetime(s.result.timestamp)
s.result = s.result[[ 'Avg_Air_Press', 'Avg_Air_Tmp','Avg_Hmt', 'Avg_Dew',
       'Avg_Wnd_Sp', 'Avg_Wnd_Dir_N','Gust_Sp', 'Wv_Hsig', 'Wv_Hmax','Wv_Tp', 
       'Avg_W_Tmp1','Wv_Avg_Spread','Wv_Avg_Dir', 'date_time']]

In [55]:
s.result.columns = 
columns = ['pres', 'atmp', 'rh', 'dewpt', 'wspd', 'wdir', 'gust', 'swvht', 'mxwvht', 'tp', 'sst', 'wvspread', 'wvdir', 'date_time']

Index(['timestamp', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND',
       'Avg_Dew', 'Avg_Hmt', 'Hmt', 'Avg_Air_Tmp', 'Avg_Air_Press', 'Gust_Sp',
       'Avg_Wnd_Sp', 'Avg_Wnd_Dir_N', 'Wv_Hsig', 'Wv_Tp', 'Wv_Hmax', 'Wv_Havg',
       'Wv_Tavg', 'Wv_H10', 'Wv_T10', 'Wv_Avg_Dir', 'Wv_Avg_Spread', 'Wv_Tsig',
       'Wv_Tp5', 'Wv_HM0', 'Wv_ZCN', 'Avg_Sal', 'DO', 'Avg_W_Tmp1',
       'Avg_W_Tmp2', 'Turb', 'Fluo', 'date_time'],
      dtype='object')

In [40]:
columns = ['pres', 'atmp', 'rh', 'dewpt', 'wspd', 'wdir', 'gust', 'swvht', 'mxwvht', 'tp', 'sst', 'wvspread', 'wvdir', 'date_time']

,timestamp,YEAR,MONTH,DAY,HOUR,MINUTE,SECOND,Avg_Dew,Avg_Hmt,Hmt,Avg_Air_Tmp,Avg_Air_Press,Gust_Sp,Avg_Wnd_Sp,Avg_Wnd_Dir_N
0,2021-11-04T04:21:40.000Z,2021,11,4,4,21,40,16.0,79.1,None,19.9,NaN,NaN,NaN,NaN
1,2021-11-04T04:51:40.000Z,2021,11,4,4,51,40,17.6,86.5,None,19.9,1005.05,8.6,7.1,13.0
2,2021-11-04T05:21:40.000Z,2021,11,4,5,21,40,17.5,85.8,None,19.9,1004.84,8.2,6.7,5.0
3,2021-11-04T05:51:40.000Z,2021,11,4,5,51,40,17.4,85.3,None,20.0,1005.06,7.0,5.1,350.0
4,2021-11-04T06:21:40.000Z,2021,11,4,6,21,40,17.5,86.8,None,19.7,1005.08,3.8,2.9,352.0
5,2021-11-04T06:51:40.000Z,2021,11,4,6,51,40,17.6,88.0,None,19.6,1005.27,5.0,3.9,42.0
6,2021-11-04T07:21:40.000Z,2021,11,4,7,21,40,17.3,86.7,None,19.6,1005.39,4.1,3.4,38.0
7,2021-11-04T07:51:40.000Z,2021,11,4,7,51,40,17.8,89.7,None,19.6,1005.75,6.9,5.6,74.0
8,2021-11-04T08:21:40.000Z,2021,11,4,8,21,40,18.4,93.2,None,19.5,1005.80,7.4,6.1,91.0
9,2021-11-04T08:51:40.000Z,2021,11,4,8,51,40,18.3,93.7,None,19.3,1006.41,5.5,4.6,75.0
10,2021-11-04T09:21:40.000Z,2021,11,4,9,21,40,18.0,90.6,None,19.5,1007.13,5.1,4.2,36.0
11,2021-11-04T09:51:40.000Z,2021,11,4,9,51,40,17.9,91.4,None,19.3,1007.54,5.2,4.2,47.0
12,2021-11-04T10:21:40.000Z,2021,11,4,10,21,40,18.2,92.2,None,19.4,1007.77,4.2,3.4,41.0
13,2021-11-04T11:21:40.000Z,2021,11,4,11,21,40,18.1,90.2,None,19.8,1008.35,2.0,1.8,69.0
14,2021-11-04T11:51:40.000Z,2021,11,4,11,51,40,18.2,89.1,None,20.1,1008.35,3.3,2.8,106.0
15,2021-11-04T12:21:40.000Z,2021,11,4,12,21,40,18.2,87.5,None,20.3,1008.20,3.8,2.5,101.0
16,2021-11-04T12:51:40.000Z,2021,11,4,12,51,40,18.0,86.3,None,20.4,1008.34,3.7,2.6,121.0
17,2021-11-04T13:21:40.000Z,2021,11,4,13,21,40,17.8,83.2,None,20.8,1008.61,3.1,2.1,101.0
18,2021-11-04T13:51:40.000Z,2021,11,4,13,51,40,18.2,86.2,None,20.6,1008.57,3.5,2.4,81.0
19,2021-11-04T14:21:40.000Z,2021,11,4,14,21,40,18.2,85.8,None,20.6,1008.60,2.7,2.0,57.0
20,2021-11-04T14:51:40.000Z,2021,11,4,14,51,40,17.9,83.6,None,20.8,1008.68,2.8,1.9,93.0
21,2021-11-04T15:51:40.000Z,2021,11,4,15,51,40,17.9,82.1,None,21.1,1008.52,3.5,2.7,103.0
22,2021-11-04T16:21:40.000Z,2021,11,4,16,21,40,17.8,82.2,None,20.9,1008.45,3.3,2.8,111.0
23,2021-11-04T16:51:40.000Z,2021,11,4,16,51,40,18.1,83.1,None,21.1,1008.22,4.1,3.0,119.0
24,2021-11-04T17:21:40.000Z,2021,11,4,17,21,40,18.0,81.4,None,21.3,1007.99,4.4,3.5,112.0
25,2021-11-04T17:51:40.000Z,2021,11,4,17,51,40,17.7,78.9,None,21.5,1007.66,4.8,3.7,110.0
26,2021-11-04T18:21:40.000Z,2021,11,4,18,21,40,18.0,80.4,None,21.5,1007.81,4.9,3.8,106.0
27,2021-11-04T18:51:40.000Z,2021,11,4,18,51,40,18.2,81.2,None,21.5,1007.74,5.9,4.6,95.0
28,2021-11-04T19:21:40.000Z,2021,11,4,19,21,40,18.5,83.3,None,21.4,1007.76,6.4,5.2,91.0
29,2021-11-04T20:51:40.000Z,2021,11,4,20,51,40,18.4,81.9,None,21.6,1008.15,6.9,5.3,78.0
30,2021-11-04T21:51:40.000Z,2021,11,4,21,51,40,18.9,85.4,None,21.4,1008.61,7.3,6.6,63.0
31,2021-11-04T22:21:40.000Z,2021,11,4,22,21,40,19.3,88.1,None,21.3,1008.89,8.4,7.0,66.0
32,2021-11-04T22:51:40.000Z,2021,11,4,22,51,40,19.2,88.2,None,21.2,1009.20,8.7,7.2,69.0
33,2021-11-04T23:21:40.000Z,2021,11,4,23,21,40,19.5,89.7,None,21.2,1009.62,8.3,6.8,72.0
34,2021-11-04T23:51:40.000Z,2021,11,4,23,51,40,19.4,89.8,None,21.2,1009.98,7.7,6.6,66.0
35,2021-11-05T00:21:40.000Z,2021,11,5,0,21,40,19.6,91.1,None,21.2,1010.17,7.6,6.5,68.0
36,2021-11-05T00:51:40.000Z,2021,11,5,0,51,40,19.9,93.7,None,21.0,1010.42,8.0,7.1,71.0
37,2021-11-05T01:21:40.000Z,2021,11,5,1,21,40,19.6,94.0,None,20.6,1010.48,9.7,8.1,58.0
38,2021-11-05T01:51:40.000Z,2021,11,5,1,51,40,19.5,94.4,None,20.4,1010.29,10.5,8.8,68.0
39,2021-11-05T02:21:40.000Z,2021,11,5,2,21,40,19.6,95.5,None,20.3,1010.15,10.4,8.8,67.0
40,2021-11-05T03:21:40.000Z,2021,11,5,3,21,40,19.4,97.5,None,19.8,1010.03,9.2,8.0,54.0
41,2021-11-05T03:51:40.000Z,2021,11,5,3,51,40,19.4,97.9,None,19.7,1009.85,8.9,7.6,65.0

In [34]:
s = SimcostaTide()

In [35]:
s.stations

,id,name,lat,lon,data_type,institution,url,flag
0,1156,DHN - RJ,-22.884722,-43.13222,tide,simcosta,304,None
1,873,Rio Grande 1 – RS,-32.188100,-52.08190,tide,simcosta,301,True
2,874,São José do Ribamar – MA,-8.393100,-34.96000,tide,simcosta,302,True
3,875,Tramandaí – RS,-30.005000,-50.12890,tide,simcosta,305,True
4,877,Imbituba – SC,-28.231100,-48.65000,tide,simcosta,308,True
5,878,Ilhabela – SP,-23.773600,-45.35470,tide,simcosta,309,True
6,879,Suape – PE,-8.393100,-34.96000,tide,simcosta,311,True
7,876,Pecém – CE,-3.531100,-38.79310,tide,simcosta,307,True

In [36]:
s.get()

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  water_l1  \
0  2022-04-25T15:44:15.000Z  2022      4   25    15      44      15   1238.14
1  2022-04-25T15:59:05.000Z  2022      4   25    15      59       5   1235.98
2  2022-04-25T16:16:17.000Z  2022      4   25    16      16      17   1236.08
3  2022-04-25T16:29:09.000Z  2022      4   25    16      29       9   1238.88
4  2022-04-25T16:44:04.000Z  2022      4   25    16      44       4   1233.20

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  \
0  2022-04-25T15:44:15.000Z  2022      4   25    15      44      15
1  2022-04-25T15:59:05.000Z  2022      4   25    15      59       5
2  2022-04-25T16:16:17.000Z  2022      4   25    16      16      17
3  2022-04-25T16:29:09.000Z  2022      4   25    16      29       9
4  2022-04-25T16:44:04.000Z  2022      4   25    16      44       4

   wind_speed  wind_direction air_temp relative_humidity  atm_pressure
0         2.9             257     None              None         500.5
1         3.3             256     None              None         500.5
2         0.7              93     None              None         500.5
3         1.8             243     None              None         500.5
4         1.2              98     None              None         500.5
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  water_l1  \
0  2022-04-25T15:52:04.000Z  2022      4   25    15      52       4    743.90
1  2022-04-25T16:07:04.000Z  2022      4   25    16       7       4    740.07
2  2022-04-25T16:23:09.000Z  2022      4   25    16      23       9    735.19
3  2022-04-25T16:37:04.000Z  2022      4   25    16      37       4    729.45
4  2022-04-25T16:53:17.000Z  2022      4   25    16      53      17    734.23

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  \
0  2022-04-25T15:52:04.000Z  2022      4   25    15      52       4
1  2022-04-25T16:07:04.000Z  2022      4   25    16       7       4
2  2022-04-25T16:23:09.000Z  2022      4   25    16      23       9
3  2022-04-25T16:37:04.000Z  2022      4   25    16      37       4
4  2022-04-25T16:53:17.000Z  2022      4   25    16      53      17

   wind_speed  wind_direction  air_temp  relative_humidity  atm_pressure
0        10.9               0     -37.7                  0        1011.2
1        11.4              10     -37.8                  0        1010.7
2        11.0               5     -37.5                  0        1010.6
3        10.6               3     -37.5                  0        1010.1
4        10.9               8     -37.6                  0        1009.8
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  water_l1  \
0  2022-04-25T15:51:04.000Z  2022      4   25    15      51       4   1243.25
1  2022-04-25T16:06:04.000Z  2022      4   25    16       6       4   1242.89
2  2022-04-25T16:22:26.000Z  2022      4   25    16      22      26   1238.38
3  2022-04-25T16:36:04.000Z  2022      4   25    16      36       4   1237.66
4  2022-04-25T16:52:26.000Z  2022      4   25    16      52      26   1237.27

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  \
0  2022-04-25T15:51:04.000Z  2022      4   25    15      51       4
1  2022-04-25T16:06:04.000Z  2022      4   25    16       6       4
2  2022-04-25T16:22:26.000Z  2022      4   25    16      22      26
3  2022-04-25T16:36:04.000Z  2022      4   25    16      36       4
4  2022-04-25T16:52:26.000Z  2022      4   25    16      52      26

   wind_speed  wind_direction  air_temp  relative_humidity  atm_pressure
0         2.2             102      28.5                 53        1016.7
1         3.9             154      28.7                 54        1016.7
2         5.6             116      28.0                 58        1016.5
3         1.9             136      28.2                 58        1016.5
4         1.4             147      27.8                 63        1016.7
                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  water_l1  \
0  2022-04-25T15:43:15.000Z  2022      4   25    15      43      15   1074.36
1  2022-04-25T15:57:04.000Z  2022      4   25    15      57       4   1070.73
2  2022-04-25T16:13:16.000Z  2022      4   25    16      13      16   1067.92
3  2022-04-25T16:27:12.000Z  2022      4   25    16      27      12   1063.48
4  2022-04-25T16:42:05.000Z  2022      4   25    16      42       5   1060.45

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  \
0  2022-04-25T15:43:15.000Z  2022      4   25    15      43      15
1  2022-04-25T15:57:04.000Z  2022      4   25    15      57       4
2  2022-04-25T16:13:16.000Z  2022      4   25    16      13      16
3  2022-04-25T16:27:12.000Z  2022      4   25    16      27      12
4  2022-04-25T16:42:05.000Z  2022      4   25    16      42       5

   wind_speed  wind_direction  air_temp  relative_humidity  atm_pressure
0           0               0      26.4                 86        1011.6
1           0               0      26.6                 80        1011.5
2           0               0      26.8                 81        1011.2
3           0               0      27.5                 82        1011.2
4           0               0      27.3                 82        1010.9
                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  water_l1  \
0  2022-04-25T15:40:04.000Z  2022      4   25    15      40       4   1179.70
1  2022-04-25T15:55:04.000Z  2022      4   25    15      55       4   1177.32
2  2022-04-25T16:10:04.000Z  2022      4   25    16      10       4   1175.52
3  2022-04-25T16:25:04.000Z  2022      4   25    16      25       4   1174.69
4  2022-04-25T16:41:25.000Z  2022      4   25    16      41      25   1168.44

                  timestamp  YEAR  MONTH  DAY  HOUR  MINUTE  SECOND  \
0  2022-04-25T15:40:04.000Z  2022      4   25    15      40       4
1  2022-04-25T15:55:04.000Z  2022      4   25    15      55       4
2  2022-04-25T16:10:04.000Z  2022      4   25    16      10       4
3  2022-04-25T16:25:04.000Z  2022      4   25    16      25       4
4  2022-04-25T16:41:25.000Z  2022      4   25    16      41      25

   wind_speed  wind_direction  air_temp  relative_humidity  atm_pressure
0           0               0      29.0                 76        1010.3
1           0               0      28.9                 78        1010.3
2           0               0      29.2                 75        1010.0
3           0               0      29.2                 74        1010.0
4           0               0      29.3                 74        1010.0

In [30]:
s.result.columns

Index(['timestamp', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND',
       'water_l1', 'wind_speed', 'wind_direction', 'air_temp',
       'relative_humidity', 'atm_pressure'],
      dtype='object')

In [52]:
s = Simcosta()

In [53]:
s.get()

id                  897
name                RJ3
lat            -22.9831
lon            -43.1745
data_type          buoy
institution    simcosta
url                   3
Name: 0, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=3&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=3&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
id                  898
name                RS2
lat            -32.1346
lon            -52098.0
data_type          buoy
institution    simcosta
url                   6
Name: 1, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=6&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=6&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
    YEAR MONTH DAY HOUR MINUTE SECOND Avg_Air_Press Avg_Air_Tmp   Hmt Avg_Hmt  \
0   2021     9   8   13     21     00       1008.25       15.90  None  100.00
1   2021     9   8   13     51     00       1006.61       15.50  None  100.00
2   2021     9   8   15     21     00       1005.88       16.10  None  100.00
3   2021     9   8   15     51     00       1005.52       16.80  None   99.80
4   2021     9   8   16     21     00       1003.89       16.60  None   99.80
5   2021     9   8   16     51     00       1005.85       16.80  None   99.80
6   2021     9   8   17     21     00       1006.56       16.80  None   99.80
7   2021     9   8   17     51     00       1006.43       16.20  None  100.00
8   2021     9   8   18     21     00       1005.64       16.00  None  100.00
9   2021     9   8   18     51     00       1005.77       16.00  None  100.00
10  2021     9   8   19     21     00       1005.86       16.40  None  100.00
11  2021     9   8   19     51     00       1005.69       16.50  None  100.00
12  2021     9   8   20     21     00       1005.95       16.50  None  100.00
13  2021     9   8   20     51     00       1005.79       16.40  None  100.00
14  2021     9   8   21     21     00       1005.81       16.30  None  100.00
15  2021     9   8   21     51     00       1006.31       16.40  None  100.00
16  2021     9   8   22     21     00       1006.60       16.60  None  100.00
17  2021     9   8   22     51     00       1006.72       16.80  None  100.00
18  2021     9   8   23     21     00       1006.89       17.20  None  100.00
19  2021     9   8   23     51     00       1006.85       17.30  None  100.00
20  2021     9   9    0     21     00       1006.84       17.30  None  100.00
21  2021     9   9    0     51     00       1007.05       17.30  None  100.00
22  2021     9   9    1     21     00       1007.23       17.50  None  100.00
23  2021     9   9    1     51     00       1007.52       17.40  None  100.00
24  2021     9   9    2     21     00       1007.47       17.70  None  100.00
25  2021     9   9    2     51     00       1007.56       18.20  None  100.00

    ...   H10  HAvg  Tsig   CDOM  YEAR MONTH DAY HOUR MINUTE SECOND
0   ...  0.19  0.10  2.30  41.99  2021     9   8   13     21      0
1   ...  0.20  0.10  2.30  41.76  2021     9   8   13     51      0
2   ...  0.20  0.11  2.80  42.53  2021     9   8   15     21      0
3   ...  0.25  0.13  3.00  42.45  2021     9   8   15     51      0
4   ...  0.22  0.12  2.70  40.34  2021     9   8   16     21      0
5   ...  0.17  0.09  2.90  37.75  2021     9   8   16     51      0
6   ...  0.14  0.07  3.00  35.23  2021     9   8   17     21      0
7   ...  0.13  0.07  2.90  32.80  2021     9   8   17     51      0
8   ...  0.13  0.07  2.60  32.41  2021     9   8   18     21      0
9   ...  0.11  0.06  2.60  32.23  2021     9   8   18     51      0
10  ...  0.10  0.05  3.00  31.82  2021     9   8   19     21      0
11  ...  0.09  0.05  2.60  32.84  2021     9   8   19     51      0
12  ...  0.07  0.04  4.50  33.04  2021     9   8   20     21      0
13  ...  0.07  0.03  5.10  31.70  2021     9   8   20     51      0
14  ...  0.07  0.04  6.60  31.63  2021     9   8   21     21      0
15  ...  0.08  0.04  6.50  29.66  2021     9   8   21     51      0
16  ...  0.10  0.05  6.40  24.38  2021     9   8   22     21      0
17  ...  0.10  0.06  6.00  20.09  2021     9   8   22     51      0
18  ...  0.09  0.04  5.70  18.88  2021     9   8   23     21      0
19  ...  0.15  0.09  5.70  17.11  2021     9   8   23     51      0
20  ...  0.17  0.08  5.60  16.48  2021     9   9    0     21      0
21  ...  0.11  0.06  5.60  14.34  2021     9   9    0     51      0
22  ...  0.07  0.03  5.50  13.98  2021     9   9    1     21      0
23  ...  0.06  0.03  5.40  15.40  2021     9   9    1     51      0
24  ...  0.04  0.02  1.80  16.30  2021     9   9    2     21      0
25  ...  0.05  0.03  5.70  12.89  2021     9   9    2     51      0

[26 rows x 49 columns]
ok1
DELETE FROM data_stations WHERE true AND station_id in (898) AND date_time >= '2021-09-08 13:21:00'
ok2
id                  899
name                RS5
lat            -32296.0
lon            -52.0239
data_type          buoy
institution    simcosta
url                  10
Name: 2, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=10&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=10&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
id                  900
name                RJ4
lat            -22.9715
lon            -43.1522
data_type          buoy
institution    simcosta
url                  12
Name: 3, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=12&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=12&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
    YEAR MONTH DAY HOUR MINUTE SECOND Avg_Air_Press Avg_Air_Tmp    Hmt  \
0   2021     9   8    3     21     00       1018.53        None  45.20
1   2021     9   8    3     51     00       1018.39        None  44.30
2   2021     9   8    4     51     00       1017.51        None  44.00
3   2021     9   8    5     21     00       1017.30        None  44.60
4   2021     9   8    5     51     00       1016.99        None  43.80
5   2021     9   8    6     51     00       1015.98        None  43.70
6   2021     9   8    7     21     00       1015.71        None  44.60
7   2021     9   8    7     51     00       1015.55        None  43.60
8   2021     9   8    8     21     00       1015.67        None  44.50
9   2021     9   8    9     21     00       1016.01        None  44.50
10  2021     9   8    9     51     00       1016.16        None  43.70
11  2021     9   8   10     21     00       1016.07        None  45.40
12  2021     9   8   10     51     00       1016.14        None  46.60
13  2021     9   8   11     21     00       1016.19        None  48.60
14  2021     9   8   12     21     00       1016.44        None  52.40
15  2021     9   8   12     51     00       1016.37        None  53.60
16  2021     9   8   13     21     00       1016.25        None  54.70
17  2021     9   8   13     51     00       1015.75        None  54.90
18  2021     9   8   14     21     00       1015.38        None  53.50
19  2021     9   8   14     51     00       1014.72        None  52.70
20  2021     9   8   15     21     00       1013.94        None  52.10
21  2021     9   8   15     51     00       1013.20        None  51.60
22  2021     9   8   16     21     00       1012.51        None  51.30
23  2021     9   8   16     51     00       1011.82        None  50.90
24  2021     9   8   17     51     00       1010.51        None  50.60
25  2021     9   8   18     51     00       1009.28        None  51.50
26  2021     9   8   19     21     00       1008.89        None  51.90
27  2021     9   8   19     51     00       1008.60        None  51.90
28  2021     9   8   20     21     00       1008.35        None  51.80
29  2021     9   8   21     21     00       1009.32        None  50.80
30  2021     9   8   22     21     00       1010.30        None  48.20
31  2021     9   9    0     21     00       1011.18        None  46.20
32  2021     9   9    1     21     00       1010.84        None  45.90
33  2021     9   9    1     51     00       1010.79        None  45.30

   Avg_Hmt  ...   H10  HAvg  Tsig  CDOM  YEAR MONTH DAY HOUR MINUTE SECOND
0     None  ...  1.88  0.93  7.70  NULL  2021     9   8    3     21     40
1     None  ...  1.75  0.92  7.50  NULL  2021     9   8    3     51     40
2     None  ...  1.94  0.96  7.80  NULL  2021     9   8    4     51     40
3     None  ...  1.80  0.95  8.60  NULL  2021     9   8    5     21     40
4     None  ...  2.01  0.99  8.80  NULL  2021     9   8    5     51     40
5     None  ...  1.86  1.02  8.70  NULL  2021     9   8    6     51     40
6     None  ...  1.82  0.97  8.20  NULL  2021     9   8    7     21     40
7     None  ...  1.95  0.95  8.60  NULL  2021     9   8    7     51     40
8     None  ...  1.74  0.95  8.30  NULL  2021     9   8    8     21     40
9     None  ...  1.87  1.02  9.00  NULL  2021     9   8    9     21     40
10    None  ...  1.95  0.91  8.50  NULL  2021     9   8    9     51     40
11    None  ...  1.65  0.87  7.40  NULL  2021     9   8   10     21     40
12    None  ...  1.91  0.96  7.90  NULL  2021     9   8   10     51     40
13    None  ...  1.64  0.87  8.80  NULL  2021     9   8   11     21     40
14    None  ...  1.78  0.96  8.40  NULL  2021     9   8   12     21     40
15    None  ...  1.81  0.97  8.50  NULL  2021     9   8   12     51     40
16    None  ...  1.90  0.98  7.90  NULL  2021     9   8   13     21     40
17    None  ...  1.81  0.92  6.90  NULL  2021     9   8   13     51     40
18    None  ...  1.83  0.98  7.80  NULL  2021     9   8   14     21     40
19    None  ...  1.70  0.89  6.90  NULL  2021     9   8   14     51     40
20    None  ...  1.99  0.95  6.90  NULL  2021     9   8   15     21     40
21    None  ...  2.03  1.07  7.60  NULL  2021     9   8   15     51     40
22    None  ...  1.97  1.06  6.80  NULL  2021     9   8   16     21     40
23    None  ...  2.05  1.08  7.20  NULL  2021     9   8   16     51     40
24    None  ...  2.02  1.12  6.90  NULL  2021     9   8   17     51     40
25    None  ...  1.84  1.03  7.10  NULL  2021     9   8   18     51     40
26    None  ...  2.03  1.11  7.70  NULL  2021     9   8   19     21     40
27    None  ...  1.99  0.96  7.60  NULL  2021     9   8   19     51     40
28    None  ...  1.84  1.02  7.70  NULL  2021     9   8   20     21     40
29    None  ...  1.95  0.98  8.10  NULL  2021     9   8   21     21     40
30    None  ...  1.97  1.06  7.80  NULL  2021     9   8   22     21     40
31    None  ...  1.90  0.99  8.90  NULL  2021     9   9    0     21     40
32    None  ...  1.96  1.01  8.00  NULL  2021     9   9    1     21     40
33    None  ...  1.87  0.95  7.60  NULL  2021     9   9    1     51     40

[34 rows x 49 columns]
ok1
DELETE FROM data_stations WHERE true AND station_id in (900) AND date_time >= '2021-09-08 03:21:00'
ok2
id                  901
name                RS3
lat            -32195.0
lon            -52.0794
data_type          buoy
institution    simcosta
url                  13
Name: 4, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=13&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=13&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
Empty DataFrame
Columns: []
Index: []
Nao ha dados para essa boia
id                  902
name                RS4
lat            -32.2454
lon            -52.0954
data_type          buoy
institution    simcosta
url                  14
Name: 5, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=14&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=14&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
   YEAR MONTH DAY HOUR MINUTE SECOND Avg_Air_Press Avg_Air_Tmp   Hmt Avg_Hmt  \
0  2021     9   8    5     21     00       1012.82       14.90  None    None
1  2021     9   8    5     51     00       1011.70       15.00  None    None
2  2021     9   8    6     21     00       1010.18       15.10  None    None
3  2021     9   8    6     51     00       1010.23       15.10  None    None
4  2021     9   8    7     21     00       1010.55       15.10  None    None
5  2021     9   8    7     51     00       1010.78       15.00  None    None
6  2021     9   8   12     21     00       1009.75       15.40  None    None
7  2021     9   8   12     51     00       1009.74       15.40  None    None
8  2021     9   8   13     51     00       1007.53       15.20  None    None

   ...   H10  HAvg  Tsig   CDOM  YEAR MONTH DAY HOUR MINUTE SECOND
0  ...  2.18  1.20  7.20  33.22  2021     9   8    5     21      0
1  ...  2.22  1.24  7.50  38.73  2021     9   8    5     51      0
2  ...  2.17  1.20  7.30  37.71  2021     9   8    6     21      0
3  ...  2.53  1.27  7.60  34.29  2021     9   8    6     51      0
4  ...  2.23  1.17  7.40  35.51  2021     9   8    7     21      0
5  ...  2.29  1.31  7.50  35.94  2021     9   8    7     51      0
6  ...  2.44  1.32  7.80  49.74  2021     9   8   12     21      0
7  ...  2.20  1.21  7.50  48.19  2021     9   8   12     51      0
8  ...  2.53  1.35  7.80  55.47  2021     9   8   13     51      0

[9 rows x 49 columns]
ok1
DELETE FROM data_stations WHERE true AND station_id in (902) AND date_time >= '2021-09-08 05:21:00'
ok2
id                  903
name                BA1
lat            -12.9895
lon            -37.4582
data_type          buoy
institution    simcosta
url                  15
Name: 6, dtype: object
http://simcosta.furg.br/api/metereo_data?boiaID=15&type=json&time1=1631069870&time2=1631156270&params=Average_wind_direction_N,Last_sampling_interval_gust_speed,Average_Dew_Point,Average_Pressure,Solar_Radiation_Average_Reading,Average_Air_Temperature,Instantaneous_Humidity,Average_Humidity,Average_wind_speed
http://simcosta.furg.br/api/oceanic_data?boiaID=15&type=json&time1=1631069870&time2=1631156270&params=H10,HAvg,Hsig_Significant_Wave_Height_m,HM0,Mean_Wave_Direction_deg,Hmax_Maximum_Wave_Height_m,ZCN,Tp5,TAvg,T10,Tsig,Mean_Spread_deg,TP_Peak_Period_seconds,Average_Salinity,Average_Temperature_deg_C,Average_Temperature_C,Average_CDOM_QSDE,Average_Chlorophyll_Fluorescence,Average_Dissolved_Oxygen,Average_Nephelometric_Turbidity_Unit_NTU,Cell_Average_Direction_N,Cell_Average_Magnitude_mm_s
    YEAR MONTH DAY HOUR MINUTE SECOND Avg_Air_Press Avg_Air_Tmp   Hmt Avg_Hmt  \
0   2021     9   8   12     51     00       1018.85       25.70  None  100.00
1   2021     9   8   13     21     00       1019.02       25.80  None  100.00
2   2021     9   8   13     51     00       1018.93       25.80  None  100.00
3   2021     9   8   14     21     00       1018.55       25.80  None  100.00
4   2021     9   8   14     51     00       1018.20       25.80  None  100.00
5   2021     9   8   15     21     00       1017.73       25.80  None  100.00
6   2021     9   8   15     51     00       1017.35       25.70  None  100.00
7   2021     9   8   16     21     00       1017.16       25.70  None  100.00
8   2021     9   8   16     51     00       1016.88       25.80  None  100.00
9   2021     9   8   17     21     00       1016.61       25.80  None  100.00
10  2021     9   8   17     51     00       1016.38       25.70  None  100.00
11  2021     9   8   18     21     00       1016.23       25.70  None  100.00
12  2021     9   8   18     51     00       1016.21       25.80  None  100.00
13  2021     9   8   19     21     00       1016.31       25.90  None  100.00
14  2021     9   8   19     51     00       1016.44       25.90  None  100.00
15  2021     9   8   20     21     00       1016.56       25.80  None  100.00
16  2021     9   8   20     51     00       1016.68       25.50  None  100.00
17  2021     9   8   21     51     00       1016.92       25.40  None  100.00
18  2021     9   8   22     21     00       1017.13       25.50  None  100.00
19  2021     9   8   22     51     00       1017.50       25.50  None  100.00
20  2021     9   8   23     21     00       1017.78       25.40  None  100.00
21  2021     9   8   23     51     00       1018.03       25.40  None  100.00
22  2021     9   9    0     21     00       1018.16       25.40  None  100.00

In [43]:
s.result.drop(columns=columns, inplace=True)

In [44]:
s.result.columns = ['pres', 'atmp', 'rh', 'dewpt', 'wspd', 'wdir', 'gust', 'swvht', 'mxwvht', 'tp', 'sst', 'wvspread', 'wvdir', 'date_time']

In [45]:
s.result = s.result.replace(to_replace =['None', 'NULL', ' ', ''],
                                        value =np.nan)

In [46]:
s.result['station_id'] = 898

In [ ]:
s.