In [1]:
"""
Created on Tue Feb 12 23:34:44 2019
@author: tobia
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from oceanoobsbrasil.db import GetData

import os
import glob
from os.path import expanduser
from dotenv import load_dotenv

from pysofar.sofar import SofarApi
from pysofar.spotter import Spotter

In [2]:
%load_ext autoreload
%autoreload 2
from oceanoobsbrasil.others.spotter_data import SpotterData

In [3]:
s = SpotterData()

In [4]:
s.get()

SPOT-0335
No sst data for buoy SPOT-0335 from 2024-01-20 to 2024-01-22
SPOT-0334
No wind data for buoy SPOT-0334 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-0334 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-0334 from 2024-01-20 to 2024-01-22
SPOT-0746
SPOT-0739
No wind data for buoy SPOT-0739 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-0739 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-0739 from 2024-01-20 to 2024-01-22
SPOT-0745
No wind data for buoy SPOT-0745 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-0745 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-0745 from 2024-01-20 to 2024-01-22
SPOT-1272
No sst data for buoy SPOT-1272 from 2024-01-20 to 2024-01-22
SPOT-1293
No sst data for buoy SPOT-1293 from 2024-01-20 to 2024-01-22
SPOT-010065
SPOT-010014
No wind data for buoy SPOT-010014 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010014 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010014 from 2024-01-20 to 2024-01-22
SPOT-010049
No wind data for buoy SPOT-010049 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010049 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010049 from 2024-01-20 to 2024-01-22
SPOT-010069
SPOT-010067
No wind data for buoy SPOT-010067 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010067 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010067 from 2024-01-20 to 2024-01-22
SPOT-010063
No wind data for buoy SPOT-010063 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010063 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010063 from 2024-01-20 to 2024-01-22
SPOT-010064
No wind data for buoy SPOT-010064 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010064 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010064 from 2024-01-20 to 2024-01-22
SPOT-010051
No wind data for buoy SPOT-010051 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010051 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010051 from 2024-01-20 to 2024-01-22
SPOT-1442
No wind data for buoy SPOT-1442 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1442 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1442 from 2024-01-20 to 2024-01-22
SPOT-010087
SPOT-010094
No wind data for buoy SPOT-010094 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010094 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010094 from 2024-01-20 to 2024-01-22
SPOT-010090
No wind data for buoy SPOT-010090 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010090 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010090 from 2024-01-20 to 2024-01-22
SPOT-010098
SPOT-010088
No wind data for buoy SPOT-010088 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010088 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010088 from 2024-01-20 to 2024-01-22
SPOT-010086
No sst data for buoy SPOT-010086 from 2024-01-20 to 2024-01-22
SPOT-010099
No wind data for buoy SPOT-010099 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010099 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010099 from 2024-01-20 to 2024-01-22
SPOT-010034
SPOT-010089
SPOT-010096
No sst data for buoy SPOT-010096 from 2024-01-20 to 2024-01-22
SPOT-010021
No wind data for buoy SPOT-010021 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010021 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010021 from 2024-01-20 to 2024-01-22
SPOT-010083
No wind data for buoy SPOT-010083 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010083 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010083 from 2024-01-20 to 2024-01-22
SPOT-1451
No wind data for buoy SPOT-1451 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1451 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1451 from 2024-01-20 to 2024-01-22
SPOT-010113
No wind data for buoy SPOT-010113 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010113 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010113 from 2024-01-20 to 2024-01-22
SPOT-010115
No wind data for buoy SPOT-010115 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010115 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010115 from 2024-01-20 to 2024-01-22
SPOT-010116
No sst data for buoy SPOT-010116 from 2024-01-20 to 2024-01-22
SPOT-010117
SPOT-010110
No sst data for buoy SPOT-010110 from 2024-01-20 to 2024-01-22
SPOT-010108
SPOT-010111
SPOT-010114
No wind data for buoy SPOT-010114 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010114 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010114 from 2024-01-20 to 2024-01-22
SPOT-010112
SPOT-010118
SPOT-010120
No wind data for buoy SPOT-010120 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010120 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010120 from 2024-01-20 to 2024-01-22
SPOT-010123
No wind data for buoy SPOT-010123 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010123 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010123 from 2024-01-20 to 2024-01-22
SPOT-010122
No wind data for buoy SPOT-010122 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010122 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010122 from 2024-01-20 to 2024-01-22
SPOT-010121
SPOT-010125
SPOT-010124
No wind data for buoy SPOT-010124 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010124 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010124 from 2024-01-20 to 2024-01-22
SPOT-010127
No wind data for buoy SPOT-010127 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-010127 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-010127 from 2024-01-20 to 2024-01-22
SPOT-010119
No sst data for buoy SPOT-010119 from 2024-01-20 to 2024-01-22
SPOT-010128
SPOT-010126
SPOT-1560
No wind data for buoy SPOT-1560 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1560 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1560 from 2024-01-20 to 2024-01-22
SPOT-1564
No wind data for buoy SPOT-1564 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1564 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1564 from 2024-01-20 to 2024-01-22
SPOT-1566
No wind data for buoy SPOT-1566 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1566 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1566 from 2024-01-20 to 2024-01-22
SPOT-1710
No sst data for buoy SPOT-1710 from 2024-01-20 to 2024-01-22
SPOT-1718
SPOT-1717
SPOT-1719
No sst data for buoy SPOT-1719 from 2024-01-20 to 2024-01-22
SPOT-010335
SPOT-010405
SPOT-010428
SPOT-010423
SPOT-1991
No wind data for buoy SPOT-1991 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1991 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1991 from 2024-01-20 to 2024-01-22
SPOT-1987
No wind data for buoy SPOT-1987 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1987 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1987 from 2024-01-20 to 2024-01-22
SPOT-1990
SPOT-1989
No wind data for buoy SPOT-1989 from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-1989 from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-1989 from 2024-01-20 to 2024-01-22
SPOT-30063D
No wind data for buoy SPOT-30063D from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-30063D from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-30063D from 2024-01-20 to 2024-01-22
SPOT-30093D
SPOT-30051D
No wind data for buoy SPOT-30051D from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-30051D from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-30051D from 2024-01-20 to 2024-01-22
SPOT-30163D
SPOT-30062D
SPOT-30400R
No sst data for buoy SPOT-30400R from 2024-01-20 to 2024-01-22
SPOT-30386R
No wind data for buoy SPOT-30386R from 2024-01-20 to 2024-01-22
No wave data for buoy SPOT-30386R from 2024-01-20 to 2024-01-22
No sst data for buoy SPOT-30386R from 2024-01-20 to 2024-01-22
SPOT-30389R

In [8]:
spotter = s.spotters[10]

In [10]:
spt_data = spotter.grab_data(
    limit=100,
    start_date=s.start_date,
    end_date=s.end_date,
    include_track=True,
    include_wind=True,
    include_surface_temp_data=True,
    include_frequency_data=True,
    include_directional_moments=True,
)

In [11]:
spt_data

{'spotterId': 'SPOT-010069',
 'waves': [{'significantWaveHeight': 4.577,
   'peakPeriod': 11.378,
   'meanPeriod': 8.951,
   'peakDirection': 267.987,
   'peakDirectionalSpread': 30.024,
   'meanDirection': 267.115,
   'meanDirectionalSpread': 38.89,
   'timestamp': '2023-08-08T01:12:25.000Z',
   'latitude': -60.67285,
   'longitude': 151.43072,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.857,
   'peakPeriod': 11.378,
   'meanPeriod': 9.314,
   'peakDirection': 270,
   'peakDirectionalSpread': 29.216,
   'meanDirection': 267.254,
   'meanDirectionalSpread': 39.398,
   'timestamp': '2023-08-08T02:12:25.000Z',
   'latitude': -60.66425,
   'longitude': 151.4525,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.673,
   'peakPeriod': 12.799,
   'meanPeriod': 9.363,
   'peakDirection': 276.442,
   'peakDirectionalSpread': 23.642,
   'meanDirection': 270.446,
   'meanDirectionalSpread': 35.924,
   'timestamp': '2023-08-08T03:12:25.000Z',
   'latitude': -60.65667,
   'longitude': 151.47858,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.703,
   'peakPeriod': 12.799,
   'meanPeriod': 9.63,
   'peakDirection': 272.66,
   'peakDirectionalSpread': 27.522,
   'meanDirection': 269.432,
   'meanDirectionalSpread': 36.498,
   'timestamp': '2023-08-08T04:12:25.000Z',
   'latitude': -60.65057,
   'longitude': 151.50625,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.049,
   'peakPeriod': 12.799,
   'meanPeriod': 10.208,
   'peakDirection': 270.862,
   'peakDirectionalSpread': 24.285,
   'meanDirection': 269.579,
   'meanDirectionalSpread': 33.841,
   'timestamp': '2023-08-08T05:12:25.000Z',
   'latitude': -60.6453,
   'longitude': 151.53268,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.758,
   'peakPeriod': 12.799,
   'meanPeriod': 9.748,
   'peakDirection': 273.032,
   'peakDirectionalSpread': 22.328,
   'meanDirection': 271.542,
   'meanDirectionalSpread': 34.095,
   'timestamp': '2023-08-08T06:12:25.000Z',
   'latitude': -60.64247,
   'longitude': 151.55762,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.948,
   'peakPeriod': 12.799,
   'meanPeriod': 10.058,
   'peakDirection': 275.367,
   'peakDirectionalSpread': 19.751,
   'meanDirection': 275.767,
   'meanDirectionalSpread': 31.463,
   'timestamp': '2023-08-08T07:12:25.000Z',
   'latitude': -60.6444,
   'longitude': 151.57878,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.308,
   'peakPeriod': 12.799,
   'meanPeriod': 10.13,
   'peakDirection': 278.079,
   'peakDirectionalSpread': 21.126,
   'meanDirection': 277.633,
   'meanDirectionalSpread': 31.263,
   'timestamp': '2023-08-08T08:12:25.000Z',
   'latitude': -60.65173,
   'longitude': 151.59683,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.973,
   'peakPeriod': 12.799,
   'meanPeriod': 10.159,
   'peakDirection': 278.113,
   'peakDirectionalSpread': 22.74,
   'meanDirection': 278.449,
   'meanDirectionalSpread': 32.24,
   'timestamp': '2023-08-08T09:12:25.000Z',
   'latitude': -60.66153,
   'longitude': 151.61353,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.773,
   'peakPeriod': 12.799,
   'meanPeriod': 9.935,
   'peakDirection': 279.164,
   'peakDirectionalSpread': 21.925,
   'meanDirection': 282.563,
   'meanDirectionalSpread': 33.528,
   'timestamp': '2023-08-08T10:12:25.000Z',
   'latitude': -60.67392,
   'longitude': 151.6261,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.936,
   'peakPeriod': 12.799,
   'meanPeriod': 10.01,
   'peakDirection': 282.27,
   'peakDirectionalSpread': 20.12,
   'meanDirection': 285.537,
   'meanDirectionalSpread': 32.846,
   'timestamp': '2023-08-08T11:12:25.000Z',
   'latitude': -60.6872,
   'longitude': 151.63498,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.642,
   'peakPeriod': 12.799,
   'meanPeriod': 9.572,
   'peakDirection': 282.324,
   'peakDirectionalSpread': 22.842,
   'meanDirection': 287.499,
   'meanDirectionalSpread': 35.079,
   'timestamp': '2023-08-08T12:12:25.000Z',
   'latitude': -60.70338,
   'longitude': 151.64682,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.782,
   'peakPeriod': 12.799,
   'meanPeriod': 9.453,
   'peakDirection': 284.273,
   'peakDirectionalSpread': 22.934,
   'meanDirection': 292.493,
   'meanDirectionalSpread': 35.627,
   'timestamp': '2023-08-08T13:12:25.000Z',
   'latitude': -60.72142,
   'longitude': 151.66063,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.817,
   'peakPeriod': 12.799,
   'meanPeriod': 8.949,
   'peakDirection': 284.284,
   'peakDirectionalSpread': 21.279,
   'meanDirection': 298.153,
   'meanDirectionalSpread': 37.326,
   'timestamp': '2023-08-08T14:12:25.000Z',
   'latitude': -60.73808,
   'longitude': 151.67557,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.726,
   'peakPeriod': 12.799,
   'meanPeriod': 8.749,
   'peakDirection': 286.528,
   'peakDirectionalSpread': 24.234,
   'meanDirection': 301.781,
   'meanDirectionalSpread': 38.771,
   'timestamp': '2023-08-08T15:12:25.000Z',
   'latitude': -60.75485,
   'longitude': 151.68863,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.933,
   'peakPeriod': 12.799,
   'meanPeriod': 8.705,
   'peakDirection': 286.978,
   'peakDirectionalSpread': 22.346,
   'meanDirection': 306.043,
   'meanDirectionalSpread': 38.072,
   'timestamp': '2023-08-08T16:12:25.000Z',
   'latitude': -60.7708,
   'longitude': 151.70323,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.085,
   'peakPeriod': 11.378,
   'meanPeriod': 8.591,
   'peakDirection': 285.212,
   'peakDirectionalSpread': 25.42,
   'meanDirection': 307.489,
   'meanDirectionalSpread': 38.263,
   'timestamp': '2023-08-08T17:12:25.000Z',
   'latitude': -60.7868,
   'longitude': 151.71935,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.103,
   'peakPeriod': 9.309,
   'meanPeriod': 8.47,
   'peakDirection': 304.838,
   'peakDirectionalSpread': 29.679,
   'meanDirection': 310.249,
   'meanDirectionalSpread': 38.406,
   'timestamp': '2023-08-08T18:12:25.000Z',
   'latitude': -60.80288,
   'longitude': 151.7372,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.006,
   'peakPeriod': 9.309,
   'meanPeriod': 8.556,
   'peakDirection': 309.711,
   'peakDirectionalSpread': 33.182,
   'meanDirection': 309.06,
   'meanDirectionalSpread': 38.913,
   'timestamp': '2023-08-08T19:12:25.000Z',
   'latitude': -60.8181,
   'longitude': 151.75225,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.989,
   'peakPeriod': 11.378,
   'meanPeriod': 8.637,
   'peakDirection': 287.958,
   'peakDirectionalSpread': 26.763,
   'meanDirection': 308.936,
   'meanDirectionalSpread': 39.23,
   'timestamp': '2023-08-08T20:12:25.000Z',
   'latitude': -60.83257,
   'longitude': 151.76705,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.325,
   'peakPeriod': 10.24,
   'meanPeriod': 8.711,
   'peakDirection': 306.174,
   'peakDirectionalSpread': 29.275,
   'meanDirection': 311.33,
   'meanDirectionalSpread': 37.858,
   'timestamp': '2023-08-08T21:12:25.000Z',
   'latitude': -60.84697,
   'longitude': 151.77688,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.168,
   'peakPeriod': 10.24,
   'meanPeriod': 8.563,
   'peakDirection': 313.888,
   'peakDirectionalSpread': 34.45,
   'meanDirection': 314.106,
   'meanDirectionalSpread': 39.881,
   'timestamp': '2023-08-08T22:12:25.000Z',
   'latitude': -60.86353,
   'longitude': 151.78303,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.422,
   'peakPeriod': 10.24,
   'meanPeriod': 8.706,
   'peakDirection': 314.63,
   'peakDirectionalSpread': 30.629,
   'meanDirection': 320.003,
   'meanDirectionalSpread': 39.228,
   'timestamp': '2023-08-08T23:12:25.000Z',
   'latitude': -60.88313,
   'longitude': 151.7882,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.398,
   'peakPeriod': 10.24,
   'meanPeriod': 8.616,
   'peakDirection': 313.837,
   'peakDirectionalSpread': 31.272,
   'meanDirection': 321.374,
   'meanDirectionalSpread': 38.597,
   'timestamp': '2023-08-09T00:12:25.000Z',
   'latitude': -60.90372,
   'longitude': 151.79703,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.702,
   'peakPeriod': 10.24,
   'meanPeriod': 8.899,
   'peakDirection': 322.845,
   'peakDirectionalSpread': 33.855,
   'meanDirection': 322.014,
   'meanDirectionalSpread': 39.344,
   'timestamp': '2023-08-09T01:12:25.000Z',
   'latitude': -60.92458,
   'longitude': 151.81385,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.964,
   'peakPeriod': 11.378,
   'meanPeriod': 9.077,
   'peakDirection': 302.634,
   'peakDirectionalSpread': 29.411,
   'meanDirection': 317.886,
   'meanDirectionalSpread': 38.152,
   'timestamp': '2023-08-09T02:12:25.000Z',
   'latitude': -60.94503,
   'longitude': 151.83323,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 6.094,
   'peakPeriod': 11.378,
   'meanPeriod': 9.212,
   'peakDirection': 307.337,
   'peakDirectionalSpread': 27.305,
   'meanDirection': 319.494,
   'meanDirectionalSpread': 36.882,
   'timestamp': '2023-08-09T03:12:25.000Z',
   'latitude': -60.96338,
   'longitude': 151.85492,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.377,
   'peakPeriod': 11.378,
   'meanPeriod': 9.004,
   'peakDirection': 313.65,
   'peakDirectionalSpread': 31.265,
   'meanDirection': 319.911,
   'meanDirectionalSpread': 39.86,
   'timestamp': '2023-08-09T04:12:25.000Z',
   'latitude': -60.97863,
   'longitude': 151.87593,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 6.027,
   'peakPeriod': 11.378,
   'meanPeriod': 9.4,
   'peakDirection': 309.46,
   'peakDirectionalSpread': 31.163,
   'meanDirection': 317.611,
   'meanDirectionalSpread': 37.97,
   'timestamp': '2023-08-09T05:12:25.000Z',
   'latitude': -60.99173,
   'longitude': 151.89897,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.737,
   'peakPeriod': 11.378,
   'meanPeriod': 9.347,
   'peakDirection': 310.63,
   'peakDirectionalSpread': 32.039,
   'meanDirection': 315.584,
   'meanDirectionalSpread': 38.994,
   'timestamp': '2023-08-09T06:12:25.000Z',
   'latitude': -61.00433,
   'longitude': 151.91935,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.841,
   'peakPeriod': 11.378,
   'meanPeriod': 9.46,
   'peakDirection': 313.162,
   'peakDirectionalSpread': 36.474,
   'meanDirection': 317.789,
   'meanDirectionalSpread': 41.441,
   'timestamp': '2023-08-09T07:12:25.000Z',
   'latitude': -61.01572,
   'longitude': 151.93703,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.5,
   'peakPeriod': 11.378,
   'meanPeriod': 9.403,
   'peakDirection': 312.371,
   'peakDirectionalSpread': 34.972,
   'meanDirection': 314.783,
   'meanDirectionalSpread': 40.465,
   'timestamp': '2023-08-09T08:12:25.000Z',
   'latitude': -61.02578,
   'longitude': 151.95482,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.431,
   'peakPeriod': 12.799,
   'meanPeriod': 9.089,
   'peakDirection': 283.988,
   'peakDirectionalSpread': 31.88,
   'meanDirection': 306.884,
   'meanDirectionalSpread': 40.957,
   'timestamp': '2023-08-10T03:18:25.000Z',
   'latitude': -61.23983,
   'longitude': 152.15173,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 6.309,
   'peakPeriod': 11.378,
   'meanPeriod': 9.431,
   'peakDirection': 305.829,
   'peakDirectionalSpread': 31.383,
   'meanDirection': 308.436,
   'meanDirectionalSpread': 36.455,
   'timestamp': '2023-08-10T04:18:25.000Z',
   'latitude': -61.25222,
   'longitude': 152.18073,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 6.202,
   'peakPeriod': 11.378,
   'meanPeriod': 9.399,
   'peakDirection': 302.593,
   'peakDirectionalSpread': 31.457,
   'meanDirection': 305.42,
   'meanDirectionalSpread': 37.39,
   'timestamp': '2023-08-10T05:18:25.000Z',
   'latitude': -61.26488,
   'longitude': 152.2135,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 6.613,
   'peakPeriod': 12.799,
   'meanPeriod': 9.847,
   'peakDirection': 285.352,
   'peakDirectionalSpread': 24.542,
   'meanDirection': 300.507,
   'meanDirectionalSpread': 36.51,
   'timestamp': '2023-08-10T06:18:25.000Z',
   'latitude': -61.27785,
   'longitude': 152.24765,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 7.112,
   'peakPeriod': 12.799,
   'meanPeriod': 10.275,
   'peakDirection': 286.676,
   'peakDirectionalSpread': 21.959,
   'meanDirection': 296.846,
   'meanDirectionalSpread': 34.157,
   'timestamp': '2023-08-10T07:18:25.000Z',
   'latitude': -61.2882,
   'longitude': 152.28298,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.453,
   'peakPeriod': 12.799,
   'meanPeriod': 9.735,
   'peakDirection': 292.236,
   'peakDirectionalSpread': 27.355,
   'meanDirection': 298.389,
   'meanDirectionalSpread': 38.354,
   'timestamp': '2023-08-11T00:14:29.000Z',
   'latitude': -61.38238,
   'longitude': 152.74368,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.099,
   'peakPeriod': 12.799,
   'meanPeriod': 9.391,
   'peakDirection': 291.501,
   'peakDirectionalSpread': 29.576,
   'meanDirection': 303.173,
   'meanDirectionalSpread': 41.883,
   'timestamp': '2023-08-11T01:14:29.000Z',
   'latitude': -61.38878,
   'longitude': 152.76443,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.199,
   'peakPeriod': 12.799,
   'meanPeriod': 9.434,
   'peakDirection': 289.373,
   'peakDirectionalSpread': 27.241,
   'meanDirection': 297.997,
   'meanDirectionalSpread': 40.348,
   'timestamp': '2023-08-11T02:14:29.000Z',
   'latitude': -61.39667,
   'longitude': 152.78442,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.885,
   'peakPeriod': 12.799,
   'meanPeriod': 9.296,
   'peakDirection': 295.304,
   'peakDirectionalSpread': 28.802,
   'meanDirection': 304.911,
   'meanDirectionalSpread': 41.592,
   'timestamp': '2023-08-11T03:14:29.000Z',
   'latitude': -61.40743,
   'longitude': 152.80338,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.989,
   'peakPeriod': 12.799,
   'meanPeriod': 9.253,
   'peakDirection': 295.927,
   'peakDirectionalSpread': 29.991,
   'meanDirection': 306.684,
   'meanDirectionalSpread': 40.967,
   'timestamp': '2023-08-11T04:14:29.000Z',
   'latitude': -61.42145,
   'longitude': 152.82542,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.922,
   'peakPeriod': 12.799,
   'meanPeriod': 8.999,
   'peakDirection': 297.007,
   'peakDirectionalSpread': 31.351,
   'meanDirection': 308.864,
   'meanDirectionalSpread': 40.947,
   'timestamp': '2023-08-11T05:14:29.000Z',
   'latitude': -61.43373,
   'longitude': 152.86095,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.755,
   'peakPeriod': 11.378,
   'meanPeriod': 8.782,
   'peakDirection': 303.652,
   'peakDirectionalSpread': 34.521,
   'meanDirection': 309.1,
   'meanDirectionalSpread': 40.892,
   'timestamp': '2023-08-11T06:14:29.000Z',
   'latitude': -61.44507,
   'longitude': 152.89347,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.66,
   'peakPeriod': 12.799,
   'meanPeriod': 8.751,
   'peakDirection': 296.067,
   'peakDirectionalSpread': 35.756,
   'meanDirection': 307.867,
   'meanDirectionalSpread': 41.521,
   'timestamp': '2023-08-11T07:14:29.000Z',
   'latitude': -61.45615,
   'longitude': 152.92208,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.88,
   'peakPeriod': 12.799,
   'meanPeriod': 8.874,
   'peakDirection': 293.757,
   'peakDirectionalSpread': 30.689,
   'meanDirection': 309.063,
   'meanDirectionalSpread': 40.406,
   'timestamp': '2023-08-11T08:14:29.000Z',
   'latitude': -61.46577,
   'longitude': 152.95165,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.749,
   'peakPeriod': 12.799,
   'meanPeriod': 8.826,
   'peakDirection': 293.485,
   'peakDirectionalSpread': 31.772,
   'meanDirection': 305.394,
   'meanDirectionalSpread': 40.41,
   'timestamp': '2023-08-11T09:14:29.000Z',
   'latitude': -61.47387,
   'longitude': 152.98327,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.828,
   'peakPeriod': 10.24,
   'meanPeriod': 8.724,
   'peakDirection': 318.083,
   'peakDirectionalSpread': 38.765,
   'meanDirection': 308.641,
   'meanDirectionalSpread': 40.716,
   'timestamp': '2023-08-11T10:14:29.000Z',
   'latitude': -61.47972,
   'longitude': 153.00983,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.888,
   'peakPeriod': 11.378,
   'meanPeriod': 8.887,
   'peakDirection': 300.563,
   'peakDirectionalSpread': 34.842,
   'meanDirection': 304.859,
   'meanDirectionalSpread': 41.376,
   'timestamp': '2023-08-11T11:14:29.000Z',
   'latitude': -61.48572,
   'longitude': 153.0303,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.193,
   'peakPeriod': 12.799,
   'meanPeriod': 9.235,
   'peakDirection': 289.867,
   'peakDirectionalSpread': 25.208,
   'meanDirection': 300.116,
   'meanDirectionalSpread': 37.885,
   'timestamp': '2023-08-11T12:14:29.000Z',
   'latitude': -61.49247,
   'longitude': 153.04648,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.147,
   'peakPeriod': 11.378,
   'meanPeriod': 9.198,
   'peakDirection': 296.623,
   'peakDirectionalSpread': 29.901,
   'meanDirection': 299.961,
   'meanDirectionalSpread': 37.909,
   'timestamp': '2023-08-11T13:14:29.000Z',
   'latitude': -61.50023,
   'longitude': 153.05888,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.825,
   'peakPeriod': 12.799,
   'meanPeriod': 9.11,
   'peakDirection': 285.74,
   'peakDirectionalSpread': 30.185,
   'meanDirection': 298.626,
   'meanDirectionalSpread': 40.537,
   'timestamp': '2023-08-11T14:14:29.000Z',
   'latitude': -61.5103,
   'longitude': 153.06822,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.873,
   'peakPeriod': 12.799,
   'meanPeriod': 9.075,
   'peakDirection': 282.816,
   'peakDirectionalSpread': 29.422,
   'meanDirection': 297.883,
   'meanDirectionalSpread': 40.929,
   'timestamp': '2023-08-11T15:14:29.000Z',
   'latitude': -61.52273,
   'longitude': 153.07583,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.7,
   'peakPeriod': 12.799,
   'meanPeriod': 9.105,
   'peakDirection': 284.83,
   'peakDirectionalSpread': 26.892,
   'meanDirection': 298.32,
   'meanDirectionalSpread': 41.406,
   'timestamp': '2023-08-11T16:14:29.000Z',
   'latitude': -61.53708,
   'longitude': 153.08652,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.716,
   'peakPeriod': 12.799,
   'meanPeriod': 9.051,
   'peakDirection': 283.404,
   'peakDirectionalSpread': 27.918,
   'meanDirection': 298.966,
   'meanDirectionalSpread': 40.425,
   'timestamp': '2023-08-11T17:14:29.000Z',
   'latitude': -61.55082,
   'longitude': 153.10267,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 5.111,
   'peakPeriod': 12.799,
   'meanPeriod': 9.549,
   'peakDirection': 286.587,
   'peakDirectionalSpread': 24.197,
   'meanDirection': 299.091,
   'meanDirectionalSpread': 36.749,
   'timestamp': '2023-08-11T18:14:29.000Z',
   'latitude': -61.5615,
   'longitude': 153.12582,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.652,
   'peakPeriod': 12.799,
   'meanPeriod': 8.978,
   'peakDirection': 287.075,
   'peakDirectionalSpread': 25.769,
   'meanDirection': 302.426,
   'meanDirectionalSpread': 39.051,
   'timestamp': '2023-08-11T19:14:29.000Z',
   'latitude': -61.57087,
   'longitude': 153.1503,
   'processing_source': 'embedded'},
  {'significantWaveHeight': 4.653,
   'peakPeriod': 12.799,
   'meanPeriod': 9.268,
   'peakDirection': 285.607,
   'peakDirectionalSpread': 24.528,
   'meanDirection': 298.053,

In [18]:
spec = pd.json_normalize(spt_data, record_path=['frequencyData'], meta=['spotterId'])

In [19]:
spec['buoy_id'] = spotter.id
spec.drop(columns='spotterId', inplace=True)
spec.rename(columns = {'timestamp': 'date_time',
                            }, inplace = True)
if not spec.empty:
    spec.drop(columns='processing_source', inplace=True)
    spec.date_time = pd.to_datetime(spec.date_time)
    spec.date_time = spec.date_time.dt.tz_localize(None)

In [25]:
spec.columns

Index(['frequency', 'df', 'a1', 'b1', 'a2', 'b2', 'varianceDensity',
       'direction', 'directionalSpread', 'date_time', 'latitude', 'longitude',
       'buoy_id'],
      dtype='object')

In [27]:
spec.df.iloc[0]

[0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.00977,
 0.0293,
 0.0293,
 0.0293,
 0.0293,
 0.0293,
 0.0293,
 0.2832]

In [24]:
spec = spec[['frequency', 'direction', 'date_time', 'latitude', 'longitude', 'buoy_id']]

,frequency,df,a1,b1,a2,b2,varianceDensity,direction,directionalSpread,date_time,latitude,longitude,buoy_id
0,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.172043, 0.139785, 0.178886, 0.692082, 0.851...","[0.032258, 0.11828, 0.158358, -0.01564, -0.109...","[-0.002933, -0.092864, 0.030303, 0.446725, 0.6...","[0.2913, 0.202346, 0.066471, 0.008798, -0.1681...","[0.0437504, 0.0687616, 0.1625344, 2.069248, 11...","[259.3803648314229, 229.76354982006728, 228.48...","[73.59592990499175, 73.2350341424419, 70.68967...",2023-08-08 01:12:25,-60.67285,151.43072,SPOT-010069
1,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.057674, 0.029326, 0.108504, 0.565982, 0.830...","[0.096774, 0.181818, 0.160313, -0.076246, -0.0...","[-0.044966, -0.034213, 0.049853, 0.356794, 0.6...","[0.16911, 0.218964, 0.241447, -0.064516, -0.10...","[0.8892047359999999, 1.1692728319999999, 1.253...","[210.79349866256598, 189.16250556800676, 214.0...","[76.32793362197492, 73.18768941479912, 72.7642...",2023-08-08 02:12:25,-60.66425,151.45250,SPOT-010069
2,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.129032, 0.178886, 0.320626, 0.770283, 0.907...","[0.009775, -0.00782, -0.01173, -0.048876, -0.0...","[0.226784, 0.206256, 0.335288, 0.556207, 0.761...","[0.180841, 0.099707, 0.132942, -0.065494, -0.1...","[0.12828672, 0.270065664, 0.42536448, 3.288066...","[265.66775291216055, 272.503090866612, 272.095...","[75.60430583048222, 73.41658403110996, 66.7764...",2023-08-08 03:12:25,-60.65667,151.47858,SPOT-010069
3,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.164223, 0.117302, 0.389052, 0.766373, 0.878...","[0.152493, 0.070381, -0.012708, -0.109482, -0....","[0.232649, 0.189638, 0.313783, 0.527859, 0.730...","[0.180841, 0.097752, 0.025415, -0.1652, -0.116...","[0.101274624, 0.14852505600000002, 0.405098496...","[227.12105625042906, 239.03631529838347, 271.8...","[71.37382076216637, 75.28253964468166, 63.3236...",2023-08-08 04:12:25,-60.65057,151.50625,SPOT-010069
4,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.044966, 0.134897, 0.345064, 0.828935, 0.903...","[0.101662, 0.061584, -0.067449, -0.190616, -0....","[0.131965, 0.11828, 0.242424, 0.641251, 0.7409...","[0.01564, -0.039101, -0.01173, -0.325513, -0.2...","[0.034527232000000005, 0.103534592, 0.36807065...","[203.86022958054474, 245.46206521807008, 281.0...","[76.39216399198615, 74.77968286125206, 65.2470...",2023-08-08 05:12:25,-60.64530,151.53268,SPOT-010069
...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.549365, 0.538612, 0.369501, 0.616813, 0.715...","[-0.599218, -0.56305, -0.173021, -0.325513, -0...","[-0.031281, -0.030303, 0.072336, 0.156403, 0.1...","[-0.744868, -0.725318, -0.636364, -0.56696, -0...","[0.027771904000000004, 0.06475059200000001, 0....","[317.4853012955651, 316.2707751188, 295.091617...","[35.04558612782513, 38.07611191066069, 62.3443...",2023-09-06 04:25:25,-64.05470,159.17517,SPOT-010069
447,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.410557, 0.414467, 0.305963, 0.589443, 0.720...","[-0.553275, -0.494624, -0.185728, -0.410557, -...","[-0.139785, -0.107527, -0.075269, 0.053763, 0....","[-0.411535, -0.505376, -0.569892, -0.684262, -...","[0.010743807999999999, 0.043019264, 0.43010457...","[323.4227851078978, 320.03889187554444, 301.25...","[45.19012321414658, 48.256628877736475, 64.927...",2023-09-06 05:25:25,-64.06265,159.18868,SPOT-010069
448,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.502444, 0.494624, 0.296188, 0.611926, 0.740...","[-0.568915, -0.545455, -0.211144, -0.29912, -0...","[-0.077224, -0.051808, 0.001955, 0.245357, 0.2...","[-0.592375, -0.617791, -0.619746, -0.657869, -...","[0.021487615999999998, 0.06450688, 0.376341504...","[318.550287231104, 317.79794739797126, 305.483...","[39.77648613459017, 41.607570495853075, 64.632...",2023-09-06 06:25:25,-64.07437,159.20670,SPOT-010069
449,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.57869, 0.576735, 0.244379, 0.631476, 0.7761...","[-0.498534, -0.468231, -0.176931, -0.301075, -...","[0.119257, 0.093842, 0.120235, 0.364614, 0.388...","[-0.681329, -0.628543, -0.577713, -0.637341, -...","[0.024485887999999997, 0.049021952, 0.39207526...","[310.7444761503711, 309.0719391245075, 305.904...","[39.378650668117665, 41.08749200225288, 67.710...",2023-09-06 07:25:25,-64.08888,159.22577,SPOT-010069
450,"[0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...","[0.00977, 0.00977, 0.00977, 0.00977, 0.00977, ...","[0.502444, 0.521017, 0.404692, 0.695015, 0.784...","[-0.422287, -0.468231, -0.143695, -0.255132, -...","[0.204301, 0.11437, 0.094819, 0.434995, 0.3870...","[-0.571847, -0.620723, -0.519062, -0.518084, -...","[0.015740928, 0.047287296, 0.5513840640000001,...","[310.04590328751385, 311.9456097166134, 289.54...","[47.50124241566916, 44.34418719802002, 61.2048...",2023-09-06 08:25:25,-64.10473,159.24618,SPOT-010069

In [23]:
pd.DataFrame(spec.frequency.tolist(), index= spec.index)

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
1,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
2,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
3,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
4,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
447,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
448,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
449,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543
450,0.0293,0.03906,0.04883,0.05859,0.06836,0.07813,0.08789,0.09766,0.10742,0.11719,...,0.3125,0.32227,0.33203,0.35156,0.38086,0.41016,0.43945,0.46875,0.49805,0.6543

In [22]:
spec.frequency.

0      [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
1      [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
2      [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
3      [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
4      [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
                             ...
446    [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
447    [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
448    [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
449    [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
450    [0.0293, 0.03906, 0.04883, 0.05859, 0.06836, 0...
Name: frequency, Length: 451, dtype: object

In [5]:
s.result.head()

,name,date_time,lat,lon,wspd,wdir,swvht,tp,wvdir,sst,institution,data_type,flag
0,SPOT-010065,2022-07-01 12:31:01,-55.801550,20.779683,10.0,251,3.624,11.378,264.375,-0.44,sofar,drifter,False
1,SPOT-010065,2022-07-02 10:21:19,-55.544267,21.169650,6.0,268,4.314,11.378,223.872,-0.34,sofar,drifter,False
2,SPOT-010065,2022-07-02 11:21:19,-55.536167,21.195967,10.4,251,4.193,11.378,231.800,-0.34,sofar,drifter,False
3,SPOT-010065,2022-07-03 09:15:01,-55.509783,21.737233,6.4,291,3.295,9.309,255.392,-0.40,sofar,drifter,False
4,SPOT-010065,2022-07-03 10:15:01,-55.513967,21.756583,9.2,268,3.405,10.240,253.806,-0.36,sofar,drifter,False

In [45]:
start_date = (datetime.utcnow() - timedelta(days=3)).strftime('%Y-%m-%d')
end_date = (datetime.utcnow() + timedelta(days=1)).strftime('%Y-%m-%d')

In [48]:
spt_data = s.spotters[15].grab_data(
    limit=100,
    start_date=start_date,
    end_date=end_date,
    include_track=True,
    include_wind=True,
    include_surface_temp_data=True,
    include_frequency_data=False,
    include_directional_moments=True
)

In [54]:
format_date = '%Y-%m-%dT%H:%M:%S.000Z'
wind = pd.json_normalize(spt_data, record_path=['wind'], meta=['spotterId'])
wind.loc[:,'timestamp'] = pd.to_datetime(wind.loc[:,'timestamp'], format = format_date)
wave = pd.json_normalize(spt_data, record_path=['waves'], meta=['spotterId'])
wave.loc[:,'timestamp'] = pd.to_datetime(wave.loc[:,'timestamp'], format=format_date)
sst = pd.json_normalize(spt_data, record_path=['surfaceTemp'], meta=['spotterId'])
sst.loc[:,'timestamp'] = pd.to_datetime(sst.loc[:,'timestamp'], format = format_date)

In [61]:
wave.head()

   significantWaveHeight  peakPeriod  ...  longitude    spotterId
0                  2.526      10.240  ...  -36.73440  SPOT-010098
1                  2.424      10.240  ...  -36.71477  SPOT-010098
2                  2.366      10.240  ...  -36.69637  SPOT-010098
3                  2.327       9.309  ...  -36.67853  SPOT-010098
4                  2.372       9.309  ...  -36.66300  SPOT-010098

[5 rows x 11 columns]

In [44]:
s.result

     wspd   wdir seasurfaceId  ... meanDirectionalSpread   sst   spotter_id
0     6.0  205.0          2.0  ...                  None  -0.5  SPOT-010065
1     6.4  188.0          2.0  ...                  None  -0.5  SPOT-010065
2     7.6  188.0          2.0  ...                  None  -0.5  SPOT-010065
3     6.0  211.0          2.0  ...                 60.77  -0.5  SPOT-010065
4     6.8  194.0          2.0  ...                  None -0.54  SPOT-010065
..    ...    ...          ...  ...                   ...   ...          ...
979  None   None         None  ...                  None -0.34  SPOT-010126
980  None   None         None  ...                  None -0.66  SPOT-010126
981  None   None         None  ...                  None -0.66  SPOT-010126
982  None   None         None  ...                  None -0.66  SPOT-010126
983  None   None         None  ...                  None -0.66  SPOT-010126

[54062 rows x 15 columns]

In [32]:
s.data[['date_time','latitude','longitude','wspd','wdir','swvht','peakPeriod',
                          'meanDirection', 'sst']]

              date_time   latitude  longitude  ... peakPeriod meanDirection   sst
0   2022-06-03 12:13:31  -54.79155  10.258633  ...     12.799       277.879  -0.5
1   2022-06-03 13:13:31 -54.776617   10.26305  ...     12.799       281.835  -0.5
2   2022-06-03 14:13:31  -54.76175  10.266817  ...     12.799        277.61  -0.5
3   2022-06-03 15:13:31   -54.7455   10.27225  ...     12.799       278.916  -0.5
4   2022-06-03 16:13:31 -54.730233  10.276017  ...     11.378       273.241 -0.54
..                  ...        ...        ...  ...        ...           ...   ...
755 2022-06-19 20:42:01       None       None  ...       None          None -0.34
756 2022-07-02 13:53:01       None       None  ...       None          None -0.66
757 2022-07-02 14:13:01       None       None  ...       None          None -0.66
758 2022-07-02 14:53:01       None       None  ...       None          None -0.66
759 2022-07-02 15:13:01       None       None  ...       None          None -0.66

[41356 rows x 9 columns]

In [4]:
bd = GetData()

In [4]:
bd.get(table='stations', institution=['=', 'simcosta'], data_type=['=', 'buoy'])

    id name         lat         lon data_type institution url
0  897  RJ3    -22.9831    -43.1745      buoy    simcosta   3
1  898  RS2    -32.1346 -52098.0000      buoy    simcosta   6
2  899  RS5 -32296.0000    -52.0239      buoy    simcosta  10
3  900  RJ4    -22.9715    -43.1522      buoy    simcosta  12
4  901  RS3 -32195.0000    -52.0794      buoy    simcosta  13
5  902  RS4    -32.2454    -52.0954      buoy    simcosta  14
6  903  BA1    -12.9895    -37.4582      buoy    simcosta  15

In [8]:
df = bd.get(table='data_stations', station_id=['in', [902]])

In [9]:
df.shape

(94, 22)

In [7]:
bd.post(table='data_stations', df=df)

DELETE FROM data_stations WHERE true AND station_id in (902) AND date_time >= '2021-09-06 00:21:00'

In [5]:
import time
import datetime
import operator
import urllib.request, json

import numpy as np
from oceanoobsbrasil.buoys.simcosta import Simcosta
from oceanoobsbrasil.tides.simcosta import SimcostaTide

In [6]:
s = SimcostaTide()

In [7]:
s.get()

Nao ha dados para essa boia
Nao ha dados para essa boia
Nao ha dados para essa boia

In [8]:
s = Simcosta()

In [9]:
s.get()

210
Nao ha dados para essa boia
504
Nao ha dados para essa boia
15
ok
3
ok
12
ok
14
Nao ha dados para essa boia
13
Nao ha dados para essa boia
510
ok
6
Nao ha dados para essa boia

In [5]:
from oceanoobsbrasil.buoys.pnboia import Pnboia

In [7]:
p = Pnboia()
p.get()

alcatrazes
Dados inseridos
bacia_de_santos
'date_time'
abrolhos
Dados inseridos
almirantado
'date_time'
noronha
Dados inseridos
mexilhão
'date_time'
pinguim
'date_time'
keller
'date_time'
bacia_de_campos
'date_time'
imbituba
Dados inseridos

In [43]:
s.result.drop(columns=columns, inplace=True)

In [44]:
s.result.columns = ['pres', 'atmp', 'rh', 'dewpt', 'wspd', 'wdir', 'gust', 'swvht', 'mxwvht', 'tp', 'sst', 'wvspread', 'wvdir', 'date_time']

In [45]:
s.result = s.result.replace(to_replace =['None', 'NULL', ' ', ''],
                                        value =np.nan)

In [46]:
s.result['station_id'] = 898

In [ ]:
s.