In [1]:
import pandas as pd
import numpy as np

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.chrome.options import Options
from datetime import datetime, timedelta
# from oceanoobsbrasil.db import GetData
# from oceanoobsbrasil.utils import *
from oceanobs.buoys.aqualink import AqualinkBuoy
from oceanobs.buoys.simcosta import Simcosta
from oceanobs.oceanobs_handler.db_handler import DbHandler
from oceanobs.oceanobs_handler.oceanobs_handler import OceanobsHandler
import os
from dotenv import load_dotenv

from bs4 import BeautifulSoup
import re
import chromedriver_binary
import time

%load_ext autoreload
%autoreload 2

In [2]:
# oceanobs = OceanobsHandler(method="observational_data_rico_surf", n_workers=16)
# output_data = oceanobs.run_pipeline()

In [3]:
# oceanobs = OceanobsHandler(method="observational_data_wave_check", n_workers=16)
# output_data = oceanobs.run_pipeline()

In [4]:
oceanobs = OceanobsHandler(method="remote_sensing_scatterometer", n_workers=1)
output_data = oceanobs.run_pipeline()

 [ Processing: 100% ] |###################################################| [|]

/tmp/tmp6dwz30g5/97600545_ascat_20250328_112400_metopb_64994_eps_o_250_3301_ovw.l2.nc4
/tmp/tmp6dwz30g5/97600546_ascat_20250328_130600_metopb_64995_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600547_ascat_20250328_144800_metopb_64996_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600548_ascat_20250328_180900_metopb_64998_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600549_ascat_20250328_195100_metopb_64999_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600551_ascat_20250328_231500_metopb_65001_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600550_ascat_20250328_213300_metopb_65000_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600552_ascat_20250329_005700_metopb_65002_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600553_ascat_20250329_023600_metopb_65003_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600554_ascat_20250329_041800_metopb_65004_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600555_ascat_20250329_060000_metopb_65005_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600556_ascat_20250329_074200_metopb_65006_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600557_ascat_20250329_092100_metopb_65007_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600558_ascat_20250329_110300_metopb_65008_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600559_ascat_20250329_124500_metopb_65009_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600560_ascat_20250329_142700_metopb_65010_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600561_ascat_20250329_174800_metopb_65012_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600562_ascat_20250329_193000_metopb_65013_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600563_ascat_20250329_211200_metopb_65014_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600564_ascat_20250329_225400_metopb_65015_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600565_ascat_20250330_003600_metopb_65016_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600566_ascat_20250330_021500_metopb_65017_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600567_ascat_20250330_035700_metopb_65018_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600568_ascat_20250330_053900_metopb_65019_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600570_ascat_20250330_090000_metopb_65021_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600569_ascat_20250330_072100_metopb_65020_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600573_ascat_20250330_140600_metopb_65024_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600578_ascat_20250331_015400_metopb_65031_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600571_ascat_20250330_104200_metopb_65022_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600572_ascat_20250330_122400_metopb_65023_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600574_ascat_20250330_190900_metopb_65027_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600575_ascat_20250330_205100_metopb_65028_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600577_ascat_20250331_001500_metopb_65030_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600576_ascat_20250330_223300_metopb_65029_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600581_ascat_20250331_070000_metopb_65034_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600580_ascat_20250331_051800_metopb_65033_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600582_ascat_20250331_084200_metopb_65035_eps_o_250_3301_ovw.l2_subsetted.nc4
/tmp/tmp6dwz30g5/97600579_ascat_20250331_033600_metopb_65032_eps_o_250_3301_ovw.l2_subsetted.nc4

Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████| 38/38 [00:00<00:00, 64.34it/s]

> /mnt/soutobias/code/oceanoslive/oceanobs/oceanobs/oceanobs_handler/oceanobs_handler.py(104)run_pipeline()
    102
    103         import pdb; pdb.set_trace()
--> 104         if self.coarse_data:
    105             if self.coarse_data["mode"] == "interval":
    106                 output_data = self.class_instance._coarse_data(output_data, interval=self.coarse_data["value"])

ipdb>  self.coarse_data

{'mode': 'step', 'value': 20}

ipdb>  self.coarse_data["mode"] == "step"

True

ipdb>  output_data.shape

(270513, 8)

ipdb>  output_data = output_data.iloc[:: self.coarse_data["value"]]
ipdb>  output_data.shape

(13526, 8)

ipdb>  q

In [ ]:
output_data

In [4]:
oceanobs = OceanobsHandler(method="remote_sensing_altimeter", n_workers=8)
output_data = oceanobs.run_pipeline()

Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████| 18/18 [01:00<00:00,  3.38s/it]

In [5]:
output_data

,date_time,latitude,longitude,wspd,swvht,geometry,station_type_id,institution_id
0,2025-03-29 02:57:00,-35.963258,-89.977849,13.120920,1.733,POINT (-10016288.333 -4295566.907),6,16
1,2025-03-29 02:57:30,-34.571120,-89.131880,12.712714,2.057,POINT (-9922115.495 -4105749.733),6,16
2,2025-03-29 02:58:00,-33.171156,-88.317769,15.278582,2.170,POINT (-9831489.073 -3918044.158),6,16
3,2025-03-29 02:58:30,-31.763978,-87.533057,14.209470,2.503,POINT (-9744135.333 -3732368.791),6,16
4,2025-03-29 02:59:00,-30.350147,-86.775469,16.172749,2.660,POINT (-9659801.022 -3548637.846),6,16
...,...,...,...,...,...,...,...,...
1044,2025-03-31 03:55:30,8.529713,-88.343293,6.123096,1.179,POINT (-9834330.392 953050.208),6,16
1045,2025-03-31 03:56:00,9.996953,-87.801664,5.909274,0.859,POINT (-9774036.527 1118545.553),6,16
1046,2025-03-31 03:56:30,12.438947,-86.885163,0.213822,0.179,POINT (-9672012.103 1395704.609),6,16
1047,2025-03-31 03:57:00,12.926756,-86.699474,0.602590,1.284,POINT (-9651341.298 1451365.549),6,16
1048,2025-03-31 03:57:30,14.388837,-86.136959,2.002155,0.179,POINT (-9588722.414 1618864.928),6,16

In [4]:
oceanobs = OceanobsHandler(method="water_quality_sc")
output_data = oceanobs.run_pipeline()

In [5]:
output_data

      date_time  cleaning  station_id
0    2025-03-25     False        9418
1    2025-03-18     False        9418
2    2025-03-11     False        9418
3    2025-03-06     False        9418
4    2025-02-25     False        9418
...         ...       ...         ...
1185 2025-03-25      True        9655
1186 2025-03-18      True        9655
1187 2025-03-11      True        9655
1188 2025-03-06      True        9655
1189 2025-02-25     False        9655

[1190 rows x 3 columns]

In [7]:
oceanobs = OceanobsHandler(method="water_quality_sp")
output_data = oceanobs.run_pipeline()

In [8]:
output_data

              date_time  cleaning  station_id
0   2025-03-01 03:00:00      True        9243
1   2025-03-01 03:00:00      True        9244
2   2025-03-01 03:00:00      True        9245
3   2025-03-01 03:00:00      True        9246
4   2025-03-01 03:00:00      True        9247
..                  ...       ...         ...
172 2025-03-01 03:00:00      True        9413
173 2025-03-01 03:00:00      True        9414
174 2025-03-01 03:00:00      True        9415
175 2025-03-01 03:00:00      True        9416
176 2025-03-01 03:00:00      True        9417

[177 rows x 3 columns]

In [4]:
# oceanobs = OceanobsHandler(method="gts_osmc_drifter")
# output_data = oceanobs.run_pipeline()
# output_data.head(5)

In [5]:
# oceanobs = OceanobsHandler(method="gts_osmc_float")
# output_data = oceanobs.run_pipeline()
# output_data.head(5)

In [8]:
oceanobs = OceanobsHandler(method="gts_ship")
output_data = oceanobs.run_pipeline()
output_data.head(5)

,date_time,latitude,longitude,wdir,wspd,swvht,tp,pres,atmp,sst,dewpt,swvht_swell,wvdir_swell,geometry,station_type_id,institution_id
13,2025-03-27 00:00:00+00:00,8.2,-83.5,180.0,8.9,NaN,NaN,1008.7,27.0,30.6,23.7,NaN,NaN,POINT (-9295177.481 915952.012),13,14
15,2025-03-27 00:00:00+00:00,10.1,-22.1,20.0,21.0,NaN,NaN,1012.1,22.8,25.3,19.3,NaN,NaN,POINT (-2460160.747 1130195.398),13,14
13,2025-03-27 00:00:00+00:00,8.2,-83.5,180.0,8.9,NaN,NaN,1008.7,27.0,30.6,23.7,NaN,NaN,POINT (-9295177.481 915952.012),13,14
15,2025-03-27 00:00:00+00:00,10.1,-22.1,20.0,21.0,NaN,NaN,1012.1,22.8,25.3,19.3,NaN,NaN,POINT (-2460160.747 1130195.398),13,14
25,2025-03-27 00:00:00+00:00,-29.5,12.8,NaN,NaN,NaN,NaN,1017.9,24.5,NaN,17.3,NaN,NaN,POINT (1424889.482 -3439440.061),13,14

In [5]:
oceanobs = OceanobsHandler(method="weather_station_inmet", n_workers=16)
output_data = oceanobs.run_pipeline()
output_data

In [2]:
oceanobs = OceanobsHandler(method="weather_station_metar", n_workers=13)
output_data = oceanobs.run_pipeline()
output_data

Downloading data: 100%|█████████████████████████| 24/24 [01:37<00:00,  4.05s/it]

,date_time,atmp,visibility,dewpt,wdir,wspd,gust,station_id
128,2025-03-17T01:00:00,25.0,10000.0,16.0,NaN,2.0,NaN,1355
130,2025-03-17T01:00:00,28.0,10000.0,24.0,70.0,8.0,NaN,1452
131,2025-03-17T01:00:00,25.0,10000.0,25.0,10.0,2.0,NaN,1431
154,2025-03-17T01:00:00,26.0,8000.0,13.0,200.0,4.0,NaN,1503
223,2025-03-17T01:00:00,26.0,10000.0,23.0,200.0,6.0,NaN,1358
...,...,...,...,...,...,...,...,...
213040,2025-03-16T21:30:00,29.0,10000.0,25.0,130.0,8.0,NaN,1693
213060,2025-03-16T21:32:00,-1.1,10.0,-5.6,20.0,6.0,NaN,1623
213061,2025-03-16T21:32:00,-1.1,10.0,-5.6,20.0,6.0,NaN,1643
213201,2025-03-16T21:35:00,25.0,10000.0,24.0,110.0,6.0,NaN,1685
213741,2025-03-16T21:36:00,24.0,10000.0,22.0,360.0,3.0,NaN,1395

In [5]:
# oceanobs = OceanobsHandler(method="buoy_pnboia", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")
# output_data = oceanobs.run_pipeline()
# output_data

Downloading data: 100%|█████████████████████████| 37/37 [00:02<00:00, 13.32it/s]
Errors collecting data: ['Error getting data from METOCEAN RECIFE', 'Error getting data from METOCEAN FORTALEZA', 'Error getting data from METOCEAN NITEROI', 'Error getting data from METOCEAN PORTO SEGURO', 'Error getting data from METOCEAN RIO GRANDE', 'Error getting data from METOCEAN VITORIA', 'Error getting data from METOCEAN CABO FRIO - 2', 'Error getting data from METOCEAN SANTOS', 'Error getting data from METOCEAN BACIA DE SANTOS - BM01', 'Error getting data from METOCEAN BACIA DE SANTOS - AX23', 'Error getting data from METOCEAN CRIOSFERA - INPE', 'Error getting data from TRIAXYS RIO GRANDE', 'Error getting data from METOCEAN ITAOCA', 'Error getting data from METOCEAN ITAJAI', 'Error getting data from METOCEAN ITAGUAI', 'Error getting data from METOCEAN NITEROI - 2', 'Error getting data from TRIAXYS CABO FRIO', 'Error getting data from METOCEAN BACIA DE CAMPOS - BM02', 'Error getting data from SPOTTER NORONHA', 'Error getting data from SPOTTER OPERANTAR - POTTER', 'Error getting data from METOCEAN BACIA DE CAMPOS - AX23', 'Error getting data from SPOTTER IMBITUBA', 'Error getting data from SPOTTER ANTARTICA - 1', 'Error getting data from SPOTTER ABROLHOS', 'Error getting data from SPOTTER COPACABANA', 'Error getting data from SPOTTER OPERANTAR - KELLER', 'Error getting data from SPOTTER NATAL', 'Error getting data from SPOTTER TRINDADE - UFF', 'Error getting data from SPOTTER MEXILHAO', 'Error getting data from SPOTTER OPERANTAR - PINGUIM', 'Error getting data from SPOTTER VITORIA', 'Error getting data from SPOTTER ILHA DE TRINDADE', 'Error getting data from METOCEAN MINUANO', 'Error getting data from METOCEAN CABO FRIO']

              date_time       wspd  wdir  sst  swvht    tp  wvdir  station_id
0   2025-03-08 01:12:01   0.000000   331  NaN   0.13  8.52    330        1066
1   2025-03-08 01:42:01   0.000000   108  NaN   0.10  6.82    327        1066
2   2025-03-08 03:12:01   0.777536   182  NaN   0.09  6.82    330        1066
3   2025-03-08 03:42:01   0.000000    51  NaN   0.05  6.82    335        1066
4   2025-03-08 05:12:01   0.000000    51  NaN   0.17   NaN    314        1066
..                  ...        ...   ...  ...    ...   ...    ...         ...
113 2025-03-08 21:59:19  13.218112    68  NaN   1.40  8.54     45        1073
114 2025-03-08 22:29:19  13.995648    97  NaN   1.35  8.54     47        1073
115 2025-03-08 22:59:19  13.218112    80  NaN   1.33  7.88     47        1073
116 2025-03-08 23:29:19  13.218112    97  NaN   1.33  7.88     44        1073
117 2025-03-08 23:59:19  13.218112    85  NaN   1.39  8.54     43        1073

[118 rows x 8 columns]

In [7]:
oceanobs = OceanobsHandler(method="buoy_se", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")
output_data = oceanobs.run_pipeline()
output_data

/mnt/soutobias/code/oceanoslive/oceanobs/oceanobs/buoys/se.py:88: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  def rename_columns(self, data):
Downloading data: 100%|███████████████████████████| 1/1 [00:38<00:00, 38.87s/it]

Channels,date_time,wspd,wdir,swvht_sea,tp_sea,swvht_swell,tp_swell,wvdir_swell,water_level,station_id
0,2025-03-12 17:26:00,21.1,130.0,1.0,130.34,0.36,7.76,124.88,2.17,749

In [7]:
oceanobs = OceanobsHandler(method="buoy_pe", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")
output_data = oceanobs.run_pipeline()

Downloading data: 100%|███████████████████████████| 1/1 [00:16<00:00, 16.28s/it]

driver is running
chrome is still running, we can quit
driver has died

In [25]:
oceanobs = OceanobsHandler(method="buoy_es", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")
output_data = oceanobs.run_pipeline()

Downloading data: 100%|███████████████████████████| 1/1 [00:01<00:00,  1.10s/it]

In [8]:
output_data

,date_time,wvdir,swvht,wvdir_sea,swvht_sea,wvdir_swell,swvht_swell,wspd,gust,wdir,station_id
0,2025-03-12 16:40:00,123,1.33,112,1.3,144,0.29,11.7,15.53,201,748

In [19]:
oceanobs = OceanobsHandler(method="buoy_pirata", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")
output_data = oceanobs.run_pipeline()

Downloading data: 100%|█████████████████████████| 11/11 [00:00<00:00, 11.49it/s]
Errors collecting data: ['Error getting data from Reggae', 'Error getting data from Frevo', 'Error getting data from Lambada', 'Error getting data from Forro', 'Error getting data from Samba']

In [20]:
output_data

,date_time,wdir,wspd,gust,swvht,tp,wvdir,pres,atmp,sst,dewpt,visibility,station_id
0,2025-03-08 23:00:00,76.0,11.1,NaN,NaN,NaN,NaN,1016.5,27.7,28.6,NaN,NaN,736
1,2025-03-08 22:00:00,85.0,11.9,NaN,NaN,NaN,NaN,1015.9,27.7,28.6,NaN,NaN,736
2,2025-03-08 21:00:00,97.0,9.9,NaN,NaN,NaN,NaN,1015.4,27.7,28.6,NaN,NaN,736
3,2025-03-08 20:00:00,102.0,9.1,NaN,NaN,NaN,NaN,1015.3,28.0,28.7,NaN,NaN,736
4,2025-03-08 14:00:00,86.0,11.3,NaN,NaN,NaN,NaN,1016.2,27.7,28.6,NaN,NaN,736
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2025-03-08 04:00:00,127.0,1.6,4.1,NaN,NaN,NaN,1010.0,27.2,NaN,NaN,NaN,745
133,2025-03-08 03:00:00,191.0,1.6,2.7,NaN,NaN,NaN,1010.4,27.1,NaN,NaN,NaN,745
134,2025-03-08 02:00:00,309.0,5.2,8.0,NaN,NaN,NaN,1011.2,27.0,NaN,NaN,NaN,745
135,2025-03-08 01:00:00,5.0,4.7,6.4,NaN,NaN,NaN,1012.3,26.6,NaN,NaN,NaN,745
136,2025-03-08 00:00:00,336.0,6.8,9.3,NaN,NaN,NaN,1012.4,26.7,NaN,NaN,NaN,745

In [3]:
# oceanobs = OceanobsHandler(method="weather_warning_inmet")

In [4]:
# oceanobs = OceanobsHandler(method="weather_warning_chm")

In [5]:
oceanobs = OceanobsHandler(method="buoy_simcosta", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")

In [6]:
# oceanobs = OceanobsHandler(method="pirata", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")

In [7]:
# oceanobs = OceanobsHandler(method="se_buoy", n_workers=8, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")

In [20]:
oceanobs = OceanobsHandler(method="buoy_aqualink", n_workers=1, start_date="2025-03-08T00:00:00", end_date="2025-03-09T00:00:00")

In [21]:
output_data = oceanobs.run_pipeline()

Downloading data: 100%|█████████████████████████| 43/43 [00:08<00:00,  4.80it/s]
Errors collecting data: ['No data for Coral Harbor ', 'No data for Sweepers Knoll', 'No data for Bahía Tomas, Cuajiniquil', 'No data for Keahole Point']

In [22]:
output_data

           sst                 date_time  swvht  wspd  station_id    pres
0    29.380000 2025-03-08 00:00:00+00:00  1.205   1.8         782     NaN
1    29.360000 2025-03-08 01:00:00+00:00  1.220   1.8         782     NaN
2    29.313333 2025-03-08 02:00:00+00:00  1.215   1.6         782     NaN
3    29.273333 2025-03-08 03:00:00+00:00  1.310   1.6         782     NaN
4    29.280000 2025-03-08 04:00:00+00:00  1.260   1.8         782     NaN
..         ...                       ...    ...   ...         ...     ...
919        NaN 2025-03-08 18:00:00+00:00  0.720   2.2         656  1009.9
920        NaN 2025-03-08 19:00:00+00:00  0.805   2.4         656  1010.1
921        NaN 2025-03-08 20:00:00+00:00  0.820   2.0         656  1010.6
922        NaN 2025-03-08 21:00:00+00:00  0.925   5.0         656  1011.0
923        NaN 2025-03-08 22:00:00+00:00  0.700   4.8         656  1011.4

[924 rows x 6 columns]

In [2]:
from oceanobs.buoys.aqualink import AqualinkBuoy

In [3]:
a = AqualinkBuoy()

In [9]:
stations = a.get_stations()

In [11]:
data, error = a.get_data(stations.iloc[0])

In [12]:
data

          sst                 date_time  bottom_temperature  swhvt  wspd
0   25.800000 2025-03-09 09:00:00+00:00           25.760000    NaN   NaN
1   25.770000 2025-03-09 10:00:00+00:00           25.646667  0.325   2.6
2   25.723333 2025-03-09 11:00:00+00:00           25.560000  0.360   0.8
3   25.536667 2025-03-09 12:00:00+00:00           25.126667  0.350   1.4
4   25.366667 2025-03-09 13:00:00+00:00           25.036667  0.345   0.8
..        ...                       ...                 ...    ...   ...
67  25.750000 2025-03-12 04:00:00+00:00           25.673333  0.375   1.4
68  25.686667 2025-03-12 05:00:00+00:00           25.650000  0.340   1.4
69  25.533333 2025-03-12 06:00:00+00:00           25.526667  0.375   1.4
70  25.486667 2025-03-12 07:00:00+00:00           25.473333  0.400   1.4
71  25.433333 2025-03-12 08:00:00+00:00           25.413333  0.410   1.2

[72 rows x 5 columns]

In [43]:
from oceanobs.buoys.se import SEBuoy

In [3]:
se = SEBuoy()

In [4]:
data_all = se.get()

/mnt/soutobias/code/oceanoslive/oceanoobsbrasil/oceanobs/buoys/se.py:79: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(str(soup))
Downloading data: 100%|███████████████████████████| 1/1 [00:37<00:00, 37.44s/it]

In [5]:
data_all

Channels,date_time,wspd,wdir,cspd,cdir,Box01_1544,Box02_1560,swvht_sea,swvdir_sea,tp_sea,swvht_swell,tp_swell,wvdir_swell,water_level
0,2025-03-11 09:42:00,6.8,347.0,0.3,356.65,0.25,236.75,1.01,7.53,120.43,0.57,8.26,128.53,0.84

In [5]:
stations = se.get_stations()
stations

    name  latitude  longitude identifier                           geometry
0  Celse     -19.0      -34.0      Celse  POINT (-3784862.687 -2154935.915)

In [6]:
data = se.get_data(station=stations.iloc[0])

In [7]:
dfs = pd.read_html(str(data))
len(dfs)

/tmp/ipykernel_19880/325447818.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(str(data))

7

In [17]:
data = None
for df in dfs:
    if "Channels" in df.columns:
        data = df
        break

In [18]:
data = data.set_index("Channels").T
data = data.iloc[[0]]

In [44]:
current_date = datetime.now().date()
data_time = data.index.values[0]
hour, minute = map(int, data_time.split(":"))
updated_datetime = datetime.combine(current_date,
                                    datetime.min.time()).replace(hour=hour,
                                                                 minute=minute)
data.index = [updated_datetime]
data.index.name = "date_time"
data.reset_index(inplace=True)
data["date_time"] = pd.to_datetime(data["date_time"])

In [45]:
data

Channels,date_time,WindSpeed (knots),WindDir (deg),Int0 (knots),Dir0 (deg),Int2 (knots),Dir2 (deg),SeaHm0 (m),SeaPeakPeriod (s),SeaPeakDir (deg),SwellHm0 (m),SwellPeakPeriod (s),SwellPeakDir (deg),SeaLevel (m)
0,2025-03-11 09:09:00,2.78,319.0,0.15,356.65,0.2,241.43,1.07,7.53,124.37,0.47,7.76,123.02,0.96

In [41]:

current_date = datetime.now().date()
data_time = data.index.values[0]
hour, minute = map(int, data_time.split(":"))
updated_datetime = datetime.combine(current_date, datetime.min.time()).replace(hour=hour, minute=minute)

In [43]:
updated_datetime

datetime.datetime(2025, 3, 11, 9, 9)

In [40]:
date_time = datetime.now()
data_time = data.index.values[0]
hour, minute  = data_time.split(":")

In [38]:
date_time = datetime.now()

In [39]:
date_time.hour

9

In [3]:
data = se.get()

Downloading data:   0%|                                   | 0/1 [00:00<?, ?it/s]

> /mnt/soutobias/code/oceanoslive/oceanoobsbrasil/oceanobs/buoys/se.py(84)get_data()
     82         import pdb; pdb.set_trace()
     83
---> 84         mwd = self.get_data_html("Box02_1560", soup)
     85         hm0 = self.get_data_html("Box02_1544", soup)
     86         wspd = self.get_data_html("Box01_1555", soup)

ipdb>  soup

<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta content="IE=edge" http-equiv="x-ua-compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<title>Porto Celse  -  OVERVIEW - AADI</title>
<meta content="noindex,nofollow,noarchive" name="robots"/>
<script language="JavaScript" src="../../javascript/some_tools.js" type="text/javascript"></script>
<script src="../../js/jquery.min.js" type="text/javascript"></script>
<script src="../../javascript/wz_dragdrop.js" type="text/javascript"></script>
<link href="../../styles/new.css" rel="stylesheet" type="text/css"/>
<script src="../../jsGeoView/HC__app_hmceoverview_directionText.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_hoidevidde.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_time.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box01.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box02.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box03.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box04.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box05.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box06.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box07.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box08.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box09.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box10.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box11.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box12.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box13.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box14.min.js" type="text/javascript"></script>
<script src="../../jsGeoView/HC__app_hmceoverview_Box15.min.js" type="text/javascript"></script>
<link href="favicon.ico" rel="icon" type="image/x-icon"/>
<link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>
</head>
<body style="">
<script src="../../js/highstock.js" type="text/javascript"></script>
<script src="../../js/highcharts-more.js" type="text/javascript"></script>
<script src="../../js/raphael-min.js" type="text/javascript"></script>
<script src="../../js/dateformat.js" type="text/javascript"></script>
<script src="../../js/servertime.js" type="text/javascript"></script>
<div class="boxContainer size1" id="Box01" style="position:absolute; top: 0px; left: 10px; width: 230px; height: 350px;">
<div class="boxTopContainer">
<div class="boxTopContent">
<h2>Wind</h2>
</div>
</div>
<div class="boxContent">
<table border="0" cellpadding="0" cellspacing="0" height="309" style="margin-top: 0px; white-space:nowrap;" width="220">
<tbody>
<tr>
<td colspan="2">
<p align="center">
</p><div id="Box01_arrow" style="height: 220px; margin: 0 auto"><svg height="342" style="overflow: hidden; position: relative;" version="1.1" width="512" xmlns="http://www.w3.org/2000/svg"><desc style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Created with Raphaël 2.1.0</desc><defs style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></defs></svg>
</div>
<p></p>
<h4 align="right">
<div id="Box01_text"></div>
</h4>
</td>
</tr>
<tr>
<td class="even">
<div id="Box01_1555_txt"></div>
</td>
<td align="center" class="even">
<div id="Box01_1555"></div>
</td>
</tr>
<tr>
<td>
<div id="Box01_1564_txt"></div>
</td>
<td align="center">
<div id="Box01_1564"></div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="boxContainer size1" id="Box02" style="position:absolute; top: 350px; left: 10px; width: 230px; height: 350px;">
<div class="boxTopContainer">
<div class="boxTopContent">
<h2>Waves</h2>
</div>
</div>
<div class="boxContent">
<table border="0" cellpadding="0" cellspacing="0" height="309" style="margin-top: 0px; white-space:nowrap;" width="220">
<tbody>
<tr>
<td colspan="2">

ipdb>  pd.from_html(soup)

*** AttributeError: module 'pandas' has no attribute 'from_html'

ipdb>  pd.read_html(soup)

*** TypeError: 'NoneType' object is not callable

ipdb>  q

Downloading data:   0%|                                   | 0/1 [01:29<?, ?it/s]

In [15]:
data

            date_time swvht  wvdir   wspd   gust
0 2025-03-10 17:57:00  1.15  101.0  11.92  13.68

In [1]:
from oceanobs.buoys.es import ESBuoy

In [2]:
es = ESBuoy()

In [3]:
data = es.get()

Downloading data: 100%|███████████████████████████| 1/1 [00:01<00:00,  1.78s/it]

In [4]:
data

             date_time  wdir  wspd   atmp swvht wvdir   tp     pres    rh
0  2025-03-10 17:15:00  56.0  13.7  25.01   NaN   NaN  NaN  1012.61  87.7

In [26]:
data_stations = oceanobs.class_instance.get_stations("Buoy")

In [27]:
data_stations

,identifier,name,latitude,longitude,geometry
0,510,RS-5,-32.29524500,-52.02491500,POINT (-5791387.046 -3802128.823)
1,514,RS-4,-32.24555600,-52.09613900,POINT (-5799315.666 -3795587.005)
2,14,RS-4_ANT,-32.24541670,-52.09543330,POINT (-5799237.108 -3795568.67)
3,513,RS-3,-32.19496670,-52.07936670,POINT (-5797448.582 -3788930.333)
6,506,RS-2,-32.13463330,-52.09730000,POINT (-5799444.908 -3780996.343)
7,999,LEOC,-32.06875900,-52.16182800,POINT (-5806628.132 -3772339.702)
8,210,RS-1,-32.02349000,-52.10556000,POINT (-5800364.407 -3766394.45)
12,200,SC-1,-27.27445330,-48.42101870,POINT (-5390203.145 -3157803.107)
14,504,PR-1,-25.66350000,-48.32441700,POINT (-5379449.493 -2957463.316)
18,220,SP-1,-23.83058300,-45.42216700,POINT (-5056372.501 -2732777.457)
20,518,CDRJ-1,-22.99277544,-43.09056758,POINT (-4796820.041 -2631144.973)
21,40,UFSC-1,-27.60135000,-48.45478333,POINT (-5393961.807 -3198805.483)
22,3,RJ-3,-22.98308300,-43.17447200,POINT (-4806160.238 -2629972.941)
23,12,RJ-4,-22.97155000,-43.15021670,POINT (-4803460.151 -2628578.454)
24,1,RJ-1,-22.96160000,-43.12483000,POINT (-4800634.116 -2627375.467)
25,502,RJ-2,-22.93198000,-43.14788000,POINT (-4803200.03 -2623794.839)
28,516,ES-1,-19.68640000,-39.76910000,POINT (-4427075.961 -2235917.472)
29,3330,BA-3,-16.43995600,-38.94309700,POINT (-4335125.728 -1855728.812)
31,515,BA-1,-12.98953330,-38.54180000,POINT (-4290453.55 -1458536.501)
34,3339,SE-1,-10.89100000,-36.93300000,POINT (-4111362.753 -1219748.15)
35,3340,AL-1,-9.17500000,-35.27700000,POINT (-3927017.677 -1025749.609)
36,3331,PE-1,-8.77430555,-35.08358333,POINT (-3905486.631 -980591.561)
39,3337,PE-2,-8.09045000,-34.84490000,POINT (-3878916.525 -903632.684)
40,3341,PB-1,-7.05200000,-34.78800000,POINT (-3872582.446 -787014.625)
41,3335,RN-1,-5.77052500,-35.16068100,POINT (-3914069.105 -643460.644)
42,3334,CE-1,-3.70063100,-38.45609400,POINT (-4280912.802 -412239.077)
43,3338,PNBoia Pecém,-3.53943300,-38.78405000,POINT (-4317420.697 -394258.716)
45,3342,PI-1,-2.83900000,-41.63700000,POINT (-4635009.638 -316165.435)
47,3333,MA-1,-2.53075000,-44.41525000,POINT (-4944283.013 -281813.452)
49,3332,PA-1,-0.55475300,-47.91233300,POINT (-5333576.512 -61755.786)
51,3336,AP-1,2.83859200,-50.01355300,POINT (-5567483.253 316119.961)

In [5]:
stations = oceanobs.get_db_stations()
stations.shape

(246, 8)

In [9]:
output_data

,sst,date_time,bottom_temperature,whvt,wspd,id,pres,barometric_pressure_bottom,surface_temperature
0,25.580000,2025-03-07 13:00:00+00:00,25.585000,0.330,0.4,1,NaN,NaN,NaN
1,25.526667,2025-03-07 14:00:00+00:00,25.583333,0.300,0.4,1,NaN,NaN,NaN
2,25.473333,2025-03-07 15:00:00+00:00,25.536667,0.315,0.4,1,NaN,NaN,NaN
3,25.440000,2025-03-07 16:00:00+00:00,25.503333,0.360,0.4,1,NaN,NaN,NaN
4,25.510000,2025-03-07 17:00:00+00:00,25.450000,0.370,0.6,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
64,NaN,2025-03-10 08:00:00+00:00,NaN,0.645,2.4,246,1008.8,NaN,29.68
65,NaN,2025-03-10 09:00:00+00:00,NaN,0.630,2.4,246,1009.5,NaN,29.58
66,NaN,2025-03-10 10:00:00+00:00,NaN,0.615,2.0,246,1010.1,NaN,29.56
67,NaN,2025-03-10 11:00:00+00:00,NaN,0.550,1.6,246,1010.6,NaN,29.50
68,NaN,2025-03-10 12:00:00+00:00,NaN,0.560,1.6,246,1010.8,NaN,29.46

In [38]:
db_stations = oceanobs.get_db_stations()

In [39]:
db_stations

,id,name,institution_id,geometry,station_type_id,identifier,latitude,longitude
0,1,Kealakekua,8,0101000020110F0000B6D1CE51A28D70C1ABE0E81DB4DE...,2,3254,19.477000,-155.923720
1,2,Coral Gardeners - HQ,8,0101000020110F00001655C8FE66CF6FC166AA8793342F...,2,2940,-17.491930,-149.818220
2,3,Channel Rock,8,0101000020110F000017124159266E5BC1DA28D52993AC...,2,3218,17.766700,-64.594990
3,4,Bight of Old Robinson4,8,0101000020110F000067B280648B5A60C153F7420A9932...,2,3265,26.334440,-77.021940
4,5,Bight of Old Robinson3,8,0101000020110F00001A29A37F975A60C1B3E811FCA635...,2,3256,26.347030,-77.022810
5,6,Poor Knights,8,0101000020110F0000715C17A5E08C7241FA9899047E21...,2,3293,-35.474850,174.734920
6,7,Olowalu Reef,8,0101000020110F0000ADB575623BA070C17D81199D2812...,2,1868,20.804590,-156.608030
7,8,Loko ea Fishpond,8,0101000020110F00000964F2E4D8C870C18B02A73595CA...,2,3012,21.595412,-158.102469
8,9,North Coral Gardens Palmyra Atoll,8,0101000020110F0000B29BC1D2EA3371C1122982750804...,2,2885,5.881480,-162.042110
9,10,Sweepers Knoll,8,0101000020110F0000075CFD376A6D5BC17752DFAF96A9...,2,1147,17.760160,-64.588230
10,11,Batu Kucing - Pulau Lang Tengah,8,0101000020110F0000EFF8AA2A5FD96541BFB1822051B3...,2,1047,5.789150,102.904040
11,12,Asor Landing Craft,8,0101000020110F0000E7EB7169C8AC6D415B2E805DEA1F...,2,1094,10.030010,139.761790
12,13,Isla Leones,8,0101000020110F0000BB67D5AC27DC5BC14565956F5D78...,2,1136,-45.042900,-65.606900
13,14,Soneva Fushi,8,0101000020110F0000BC5665E42C095F418B9939DAEB5E...,2,3205,5.106490,73.085670
14,15,Oil Slick,8,0101000020110F0000DFD3A5EBDB015DC147EBC3B7AAE1...,2,3390,12.200110,-68.308610
15,16,BlueNomads.Org,8,0101000020110F00009B275E9C45556A41BA44D5BEB599...,2,3207,10.305700,124.022530
16,17,"Bahía Tomas, Cuajiniquil",8,0101000020110F00003D3B7274453362C14F18C39BB5AE...,2,1119,10.931800,-85.718930
17,18,Channel Entrance,8,0101000020110F0000DC1D721607D07241FA21C088E1D3...,2,3595,-17.852760,177.205710
18,19,Pollokshields Wreck,8,0101000020110F00007A57C67D3A815BC1B4C0028BFFFB...,2,3197,32.271780,-64.770490
19,20,HIMB Coral Nursery,8,0101000020110F0000314E53B65CC070C1F6B0A59898A4...,2,1042,21.432870,-157.790260
20,21,Carysfort North,8,0101000020110F00004B95A646BC0761C15FBB8C457526...,2,3645,25.223930,-80.208220
21,22,Looe Key Reef,8,0101000020110F0000C205895DBA4861C164DA9051E283...,2,3649,24.545620,-81.403920
22,23,Sombrero Reef,8,0101000020110F0000A82E6340B93861C10798E9C3EB96...,2,3648,24.625240,-81.109480
23,24,Horseshoe Reef,8,0101000020110F0000FC24835C6F0C61C16E91931CC511...,2,3652,25.137820,-80.294680
24,25,Arraial do Cabo - Prainha da Ilha,8,0101000020110F00009E28F69095D651C1840EE663E614...,2,1187,-23.001010,-42.006860
25,26,Newfound Harbor,8,0101000020110F00007A55044BA64761C1B4E5398C7F94...,2,3650,24.615110,-81.384080
26,27,Kalama,8,0101000020110F0000CF0DB463209C70C1023411553600...,2,2188,20.727410,-156.456970
27,28,Ta'ū Harbor Backyard Buoys,8,0101000020110F000003D2E8D89DFE71C1970CE38D9079...,2,8807,-14.259320,-169.500430
28,29,East Flower Garden Bank,8,0101000020110F0000DDFE9E7D8ADF63C15C2970B35BC4...,2,3364,27.978500,-93.598020
29,30,Cocos (Keeling)Islands Lagoon,8,0101000020110F00006E1317402B9164414C84666DC9C8...,2,3313,-12.144180,96.865930
30,31,Carysfort South,8,0101000020110F00001CC866EA5F0861C1CF5090166322...,2,3646,25.206990,-80.219980
31,32,Puerto Morelos,8,0101000020110F00009C315FC2B27162C1D6C6725CB31B...,2,1085,20.845610,-86.867430
32,33,Majuro (Backyard Buoys),8,0101000020110F00004410BAFADB2C7241A171951F5C5B...,2,3678,7.151050,171.201930
33,34,Keahole Point,8,0101000020110F0000DF72F465649170C114CF42968A18...,2,1006,19.727600,-156.062000
34,35,Isla Gran Robredo,8,0101000020110F0000DBD544607F0D5CC1FE5209DE6F85...,2,1138,-45.127800,-66.060790
35,36,"SiMCosta PE-1 / Tamandaré, PE",8,0101000020110F0000E44E007391CC4DC1BE1E205BD0EC...,2,3331,-8.774240,-35.086640
36,37,Fernando de Noronha Archipelago - Baía dos Gol...,8,0101000020110F0000B3C7EDB5048F4BC12AFA5E7CE83D...,2,1186,-3.859350,-32.448670
37,38,Coral Gardeners PHN nursery,8,0101000020110F00008CF850563BD06FC19A4AD27C1C2B...,2,3359,-17.482950,-149.833480
38,39,Kaʻūpūlehu,8,0101000020110F0000BA4404BA958F70C1D0DF7DFAC730...,2,3250,19.832510,-155.995500
39,40,Faleasao - Backyard Buoys,8,0101000020110F0000FFA6308220FF71C1FB7AEFEA1468...,2,8804,-14.220350,-169.519210
40,41,Pehlung (Backyard Buoys),8,0101000020110F0000546881002FC87041CDA6D400E252...,2,8808,6.849210,158.078050

In [40]:
data_stations = oceanobs.class_instance.get_stations()

In [41]:
data_stations.head()

,identifier,name,geometry,latitude,longitude
142,3254,Kealakekua,POINT (-17357349.113 2211176.234),19.47700,-155.92372
197,2940,Coral Gardeners - HQ,POINT (-16677687.962 -1978164.576),-17.49193,-149.81822
249,3218,Channel Rock,POINT (-7190681.395 2010259.163),17.76670,-64.59499
344,3265,Bight of Old Robinson4,POINT (-8574043.141 3040562.08),26.33444,-77.02194
345,3256,Bight of Old Robinson3,POINT (-8574139.989 3042125.969),26.34703,-77.02281

In [44]:
stations = oceanobs.update_db_stations(data_stations, db_stations)

In [45]:
stations

,id,name,institution_id,geometry,station_type_id,identifier,latitude,longitude
0,1,Kealakekua,8,0101000020110F0000B6D1CE51A28D70C1ABE0E81DB4DE...,2,3254,19.47700,-155.92372
1,2,Coral Gardeners - HQ,8,0101000020110F00001655C8FE66CF6FC166AA8793342F...,2,2940,-17.49193,-149.81822
2,3,Channel Rock,8,0101000020110F000017124159266E5BC1DA28D52993AC...,2,3218,17.76670,-64.59499
3,4,Bight of Old Robinson4,8,0101000020110F000067B280648B5A60C153F7420A9932...,2,3265,26.33444,-77.02194
4,5,Bight of Old Robinson3,8,0101000020110F00001A29A37F975A60C1B3E811FCA635...,2,3256,26.34703,-77.02281
...,...,...,...,...,...,...,...,...
118,119,Fernando de Noronha Archipelago - Baía dos Gol...,8,0101000020110F0000B3C7EDB5048F4BC12AFA5E7CE83D...,2,1186,-3.85935,-32.44867
119,120,Coral Gardeners PHN nursery,8,0101000020110F00008CF850563BD06FC19A4AD27C1C2B...,2,3359,-17.48295,-149.83348
120,121,Kaʻūpūlehu,8,0101000020110F0000BA4404BA958F70C1D0DF7DFAC730...,2,3250,19.83251,-155.99550
121,122,Faleasao - Backyard Buoys,8,0101000020110F0000FFA6308220FF71C1FB7AEFEA1468...,2,8804,-14.22035,-169.51921
122,123,Pehlung (Backyard Buoys),8,0101000020110F0000546881002FC87041CDA6D400E252...,2,8808,6.84921,158.07805

In [ ]:
db_station = db_stations[db_stations["identifier"] == station["id"]]

In [ ]:
db_station

In [ ]:
for station in data_stations.iterrows():
    station = station[1]
    db_station = db_stations[db_stations["identifier"] == station["identifier"]]
    if len(db_station) == 0:
        continue
    db_station = db_station.iloc[0]
    if db_station["position"] != station["position"]:
        self.db_handler.post(table="stations", data=station.to_dict())
# Remove stations that are already in the database

In [26]:
stations = data_stations[~data_stations["identifier"].isin(db_stations["identifier"])]
# if len(stations) > 0:
#     self.db_handler.feed_bd(table="stations", df=stations)

In [30]:
if len(stations) > 0:
    oceanobs.db_handler.feed_bd(table="stations", data=stations)

AttributeError: 'Engine' object has no attribute 'execute'

In [23]:
stations = a.get_stations()

In [28]:
data = a.get(stations=stations)

Downloading data: 100%|█████████████████████████| 41/41 [00:08<00:00,  5.04it/s]

In [29]:
data.columns

Index(['sst', 'date_time', 'bottom_temperature', 'whvt', 'wspd', 'identifier',
       'pres', 'barometric_pressure_bottom', 'surface_temperature'],
      dtype='object')

In [30]:
data

,sst,date_time,bottom_temperature,whvt,wspd,identifier,pres,barometric_pressure_bottom,surface_temperature
0,25.775000,2025-03-07 10:00:00+00:00,25.720000,0.310,0.4,3254,NaN,NaN,NaN
1,25.706667,2025-03-07 11:00:00+00:00,25.630000,0.335,0.4,3254,NaN,NaN,NaN
2,25.650000,2025-03-07 12:00:00+00:00,25.593333,0.305,0.4,3254,NaN,NaN,NaN
3,25.600000,2025-03-07 13:00:00+00:00,25.590000,0.330,0.4,3254,NaN,NaN,NaN
4,25.526667,2025-03-07 14:00:00+00:00,25.583333,0.300,0.4,3254,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
65,NaN,2025-03-10 06:00:00+00:00,NaN,0.650,3.0,8808,1007.5,NaN,29.84
66,NaN,2025-03-10 07:00:00+00:00,NaN,0.650,2.8,8808,1008.1,NaN,29.82
67,NaN,2025-03-10 08:00:00+00:00,NaN,0.645,2.4,8808,1008.8,NaN,29.68
68,NaN,2025-03-10 09:00:00+00:00,NaN,0.630,2.4,8808,1009.5,NaN,29.58
69,NaN,2025-03-10 10:00:00+00:00,NaN,0.610,2.0,8808,1010.1,NaN,29.56

In [1]:
from oceanobs.buoys.simcosta import Simcosta

,identifier,name,latitude,longitude,geometry
0,510,RS-5,-32.29524500,-52.02491500,POINT (-5791387.046 -3802128.823)
1,514,RS-4,-32.24555600,-52.09613900,POINT (-5799315.666 -3795587.005)
2,14,RS-4_ANT,-32.24541670,-52.09543330,POINT (-5799237.108 -3795568.67)
3,513,RS-3,-32.19496670,-52.07936670,POINT (-5797448.582 -3788930.333)
6,506,RS-2,-32.13463330,-52.09730000,POINT (-5799444.908 -3780996.343)
7,999,LEOC,-32.06875900,-52.16182800,POINT (-5806628.132 -3772339.702)
8,210,RS-1,-32.02349000,-52.10556000,POINT (-5800364.407 -3766394.45)
12,200,SC-1,-27.27445330,-48.42101870,POINT (-5390203.145 -3157803.107)
14,504,PR-1,-25.66350000,-48.32441700,POINT (-5379449.493 -2957463.316)
18,220,SP-1,-23.83058300,-45.42216700,POINT (-5056372.501 -2732777.457)
20,518,CDRJ-1,-22.99277544,-43.09056758,POINT (-4796820.041 -2631144.973)
21,40,UFSC-1,-27.60135000,-48.45478333,POINT (-5393961.807 -3198805.483)
22,3,RJ-3,-22.98308300,-43.17447200,POINT (-4806160.238 -2629972.941)
23,12,RJ-4,-22.97155000,-43.15021670,POINT (-4803460.151 -2628578.454)
24,1,RJ-1,-22.96160000,-43.12483000,POINT (-4800634.116 -2627375.467)
25,502,RJ-2,-22.93198000,-43.14788000,POINT (-4803200.03 -2623794.839)
28,516,ES-1,-19.68640000,-39.76910000,POINT (-4427075.961 -2235917.472)
29,3330,BA-3,-16.43995600,-38.94309700,POINT (-4335125.728 -1855728.812)
31,515,BA-1,-12.98953330,-38.54180000,POINT (-4290453.55 -1458536.501)
34,3339,SE-1,-10.89100000,-36.93300000,POINT (-4111362.753 -1219748.15)
35,3340,AL-1,-9.17500000,-35.27700000,POINT (-3927017.677 -1025749.609)
36,3331,PE-1,-8.77430555,-35.08358333,POINT (-3905486.631 -980591.561)
39,3337,PE-2,-8.09045000,-34.84490000,POINT (-3878916.525 -903632.684)
40,3341,PB-1,-7.05200000,-34.78800000,POINT (-3872582.446 -787014.625)
41,3335,RN-1,-5.77052500,-35.16068100,POINT (-3914069.105 -643460.644)
42,3334,CE-1,-3.70063100,-38.45609400,POINT (-4280912.802 -412239.077)
43,3338,PNBoia Pecém,-3.53943300,-38.78405000,POINT (-4317420.697 -394258.716)
45,3342,PI-1,-2.83900000,-41.63700000,POINT (-4635009.638 -316165.435)
47,3333,MA-1,-2.53075000,-44.41525000,POINT (-4944283.013 -281813.452)
49,3332,PA-1,-0.55475300,-47.91233300,POINT (-5333576.512 -61755.786)
51,3336,AP-1,2.83859200,-50.01355300,POINT (-5567483.253 316119.961)

In [10]:
s = Simcosta(station_type="Buoy", n_workers=8)

In [11]:
stations = s.get_stations()

In [12]:
data = s.get()

No data available for the station 14                     | 0/31 [00:00<?, ?it/s]
No data available for the station 513            | 1/31 [00:01<00:42,  1.43s/it]
No data available for the station 999
No data available for the station 200
No data available for the station 510
No data available for the station 220            | 7/31 [00:01<00:04,  5.90it/s]
Error getting data for station 40                | 9/31 [00:02<00:06,  3.40it/s]
No data available for the station 3
No data available for the station 1
No data available for the station 502           | 13/31 [00:02<00:03,  6.00it/s]
Error getting data for station 3330             | 15/31 [00:03<00:03,  4.87it/s]
Error getting data for station 3339
Error getting data for station 3340█▋           | 17/31 [00:04<00:03,  4.55it/s]
Error getting data for station 3337███▎         | 19/31 [00:04<00:02,  4.16it/s]
Error getting data for station 3335█████▋       | 22/31 [00:04<00:01,  5.57it/s]
Error getting data for station 3341███████▎     | 24/31 [00:05<00:01,  5.10it/s]
Error getting data for station 3334
Error getting data for station 3333
Error getting data for station 3342
Error getting data for station 3336█████████▊   | 27/31 [00:05<00:00,  4.96it/s]
Error getting data for station 3332
Downloading data: 100%|█████████████████████████| 31/31 [00:06<00:00,  4.77it/s]

In [16]:
from oceanobs.buoys.pirata import Pirata

In [24]:
p = Pirata()

In [25]:
stations = p.get_stations()

In [26]:
stations

,name,latitude,longitude,identifier,geometry
0,Espirito Santo,-19.0,-34.0,31005,POINT (-3784862.687 -2154935.915)
1,Salvador,-14.0,-32.0,31004,POINT (-3562223.705 -1574216.548)
2,Paraiba,-8.0,-30.0,31003,POINT (-3339584.724 -893463.751)
3,Samba,0.0,-35.0,31001,POINT (-3896182.178 0)
4,Frevo,4.0,-38.0,31002,POINT (-4230140.65 445640.11)
5,Lambada,8.0,-38.0,13009,POINT (-4230140.65 893463.751)
6,Forro,12.0,-38.0,41026,POINT (-4230140.65 1345708.408)
7,Reggae,15.0,-38.0,41139,POINT (-4230140.65 1689200.14)
8,20N,20.0,-38.0,13008,POINT (-4230140.65 2273030.927)
9,Jazz,0.0,-23.0,31007,POINT (-2560348.288 0)
10,NE Extension,4.0,-23.0,31006,POINT (-2560348.288 445640.11)

In [31]:
p.get_data(stations.iloc[0])

,date_time,wdir,wspd,gust,swvht,tp,wvdir,pres,atmp,sst,dewpt,visibility
1,2025-03-10 14:00:00,2.0,10.7,NaN,NaN,NaN,NaN,1015.4,27.8,28.6,NaN,NaN
2,2025-03-10 11:00:00,358.0,11.3,NaN,NaN,NaN,NaN,1016.0,27.8,28.6,NaN,NaN
3,2025-03-10 10:00:00,11.0,9.5,NaN,NaN,NaN,NaN,1015.4,27.7,28.5,NaN,NaN
4,2025-03-10 09:00:00,11.0,11.5,NaN,NaN,NaN,NaN,1014.5,27.8,28.5,NaN,NaN
5,2025-03-10 08:00:00,14.0,10.9,NaN,NaN,NaN,NaN,1014.1,27.6,28.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
545,2025-01-24 10:00:00,88.0,7.2,NaN,NaN,NaN,NaN,1015.2,27.1,28.2,NaN,NaN
546,2025-01-24 09:00:00,80.0,8.2,NaN,NaN,NaN,NaN,1014.9,27.2,28.2,NaN,NaN
547,2025-01-24 08:00:00,46.0,9.1,NaN,NaN,NaN,NaN,1013.9,26.9,28.2,NaN,NaN
548,2025-01-24 03:00:00,46.0,12.4,NaN,NaN,NaN,NaN,1014.6,27.2,28.2,NaN,NaN
549,2025-01-24 02:00:00,55.0,9.9,NaN,NaN,NaN,NaN,1015.5,27.3,28.2,NaN,NaN

In [34]:
data = p.get()

Downloading data:  36%|█████████▍                | 4/11 [00:00<00:01,  4.00it/s]

Error getting data from https://www.ndbc.noaa.gov/data/realtime2/31001.txt

Downloading data:  45%|███████████▊              | 5/11 [00:01<00:01,  3.10it/s]

Error getting data from https://www.ndbc.noaa.gov/data/realtime2/31002.txt

Downloading data:  55%|██████████████▏           | 6/11 [00:01<00:01,  2.60it/s]

Error getting data from https://www.ndbc.noaa.gov/data/realtime2/13009.txt

Downloading data:  64%|████████████████▌         | 7/11 [00:02<00:01,  2.42it/s]

Error getting data from https://www.ndbc.noaa.gov/data/realtime2/41026.txt

Downloading data:  82%|█████████████████████▎    | 9/11 [00:02<00:00,  2.79it/s]

Error getting data from https://www.ndbc.noaa.gov/data/realtime2/41139.txt

Downloading data: 100%|█████████████████████████| 11/11 [00:03<00:00,  3.31it/s]

In [35]:
data

,date_time,wdir,wspd,gust,swvht,tp,wvdir,pres,atmp,sst,dewpt,visibility
0,2025-03-10 14:00:00,2.0,10.7,NaN,NaN,NaN,NaN,1015.4,27.8,28.6,NaN,NaN
1,2025-03-10 11:00:00,358.0,11.3,NaN,NaN,NaN,NaN,1016.0,27.8,28.6,NaN,NaN
2,2025-03-10 10:00:00,11.0,9.5,NaN,NaN,NaN,NaN,1015.4,27.7,28.5,NaN,NaN
3,2025-03-10 09:00:00,11.0,11.5,NaN,NaN,NaN,NaN,1014.5,27.8,28.5,NaN,NaN
4,2025-03-10 08:00:00,14.0,10.9,NaN,NaN,NaN,NaN,1014.1,27.6,28.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5900,2025-01-24 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.4,NaN,NaN,NaN
5901,2025-01-24 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.7,NaN,NaN,NaN
5902,2025-01-24 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN,NaN,NaN
5903,2025-01-24 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN,NaN,NaN
5904,2025-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.9,NaN,NaN,NaN

In [41]:
stations = oceanobs.get_db_stations()

In [42]:
stations

,id,name,institution_id,geometry,station_type_id,identifier,latitude,longitude
0,705,RS-5,3,0101000020110F0000F29DF7C2A61756C134065E690802...,2,510,-32.295245,-52.024915
1,706,RS-4,3,0101000020110F000044119CEA641F56C1DC179F8041F5...,2,514,-32.245556,-52.096139
2,707,RS-4_ANT,3,0101000020110F00000719E346511F56C12BBDCC5538F5...,2,14,-32.245417,-52.095433
3,708,RS-3,3,0101000020110F000051863D25921D56C1B7EEA12A41E8...,2,513,-32.194967,-52.079367
4,709,RS-2,3,0101000020110F00003DD4173A851F56C1562FF62BC2D8...,2,506,-32.134633,-52.097300
5,710,LEOC,3,0101000020110F0000C6836F08892656C106CCE6D9D9C7...,2,999,-32.068759,-52.161828
6,711,RS-1,3,0101000020110F00009258071A6B2056C1246192393DBC...,2,210,-32.023490,-52.105560
7,712,SC-1,3,0101000020110F00005DD54DC9DE8F54C1BACBA38D9517...,2,200,-27.274453,-48.421019
8,713,PR-1,3,0101000020110F0000A795925F5E8554C1C63582A84B90...,2,504,-25.663500,-48.324417
9,714,SP-1,3,0101000020110F0000E61E1320DD4953C1F2778CBA74D9...,2,220,-23.830583,-45.422167
10,715,CDRJ-1,3,0101000020110F000030B99F02654C52C14B907F7CF412...,2,518,-22.992775,-43.090568
11,716,UFSC-1,3,0101000020110F00004E83A2738A9354C15023C7BDAA67...,2,40,-27.601350,-48.454783
12,717,RJ-3,3,0101000020110F00001472400F845552C173F76A78AA10...,2,3,-22.983083,-43.174472
13,718,RJ-4,3,0101000020110F00002478A409E15252C11214143AF10D...,2,12,-22.971550,-43.150217
14,719,RJ-1,3,0101000020110F0000AEF16E871E5052C1FA79CEBB970B...,2,1,-22.961600,-43.124830
15,720,RJ-2,3,0101000020110F0000BC39F201A05252C10BB66A6B9904...,2,502,-22.931980,-43.147880
16,721,ES-1,3,0101000020110F0000DB0C86FD50E350C108E36BBC060F...,2,516,-19.686400,-39.769100
17,722,BA-3,3,0101000020110F00006EC8966E858950C1B33CCCCFF050...,2,3330,-16.439956,-38.943097
18,723,BA-1,3,0101000020110F0000BE653763E55D50C123E64E806841...,2,515,-12.989533,-38.541800
19,724,SE-1,3,0101000020110F000076A37160015E4FC111735726A49C...,2,3339,-10.891000,-36.933000
20,725,AL-1,3,0101000020110F000017939ED6F4F54DC124589E37AB4D...,2,3340,-9.175000,-35.277000
21,726,PE-1,3,0101000020110F000068F5D450E7CB4DC1A8386D1FDFEC...,2,3331,-8.774306,-35.083583
22,727,PE-2,3,0101000020110F000074C32A4302984DC17E33035EA193...,2,3337,-8.090450,-34.844900
23,728,PB-1,3,0101000020110F00002A3C0D39A38B4DC19523FB3F8D04...,2,3341,-7.052000,-34.788000
24,729,RN-1,3,0101000020110F00001A356C8DAADC4DC1FCDD9A4909A3...,2,3335,-5.770525,-35.160681
25,730,CE-1,3,0101000020110F0000A39C5333945450C13A8E974E3C29...,2,3334,-3.700631,-38.456094
26,731,PNBoia Pecém,3,0101000020110F000013069A2C3B7850C15848B9DC4A10...,2,3338,-3.539433,-38.784050
27,732,PI-1,3,0101000020110F0000139BD76860AE51C1B030C9BD154C...,2,3342,-2.839000,-41.637000
28,733,MA-1,3,0101000020110F00005276DCC066DC52C161E08ECE5533...,2,3333,-2.530750,-44.415250
29,734,PA-1,3,0101000020110F0000A528C920925854C1E84A052A7927...,2,3332,-0.554753,-47.912333
30,735,AP-1,3,0101000020110F0000939A2CD0FE3C55C1E0DA3FD85F4B...,2,3336,2.838592,-50.013553